language: cpp
compiler:
  - gcc
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
install:
  - wget http://biopp.univ-montp2.fr/repos/apt/debian/pool/main/libb/libbpp-core/libbpp-core-dev_2.0.3-1_amd64.deb
  - sudo dpkg -i libbpp-core-dev_2.0.3-1_amd64.deb
  - wget http://biopp.univ-montp2.fr/repos/apt/debian/pool/main/libb/libbpp-seq/libbpp-seq-dev_2.0.3-1_amd64.deb
  - sudo dpkg -i libbpp-seq-dev_2.0.3-1_amd64.deb
  - sudo apt-get install cxxtest