.TH "Circal::MultiplePseudoCircularAlignmentFactory" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MultiplePseudoCircularAlignmentFactory \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MultiplePseudoCircularAlignmentFactory.h>\fP
.PP
Inherits \fBCircal::MultipleAlignmentFactory\fP, and \fBCircal::PseudoCircularAlignmentFactory\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiplePseudoCircularAlignmentFactory\fP ()"
.br
.ti -1c
.RI "virtual \fB~MultiplePseudoCircularAlignmentFactory\fP ()"
.br
.ti -1c
.RI "\fBAlignment\fP \fBNMWalignMultiple\fP (const bpp::VectorSequenceContainer *input, const \fBScoringModel\fP *scoreM, const int &delta, bool verbose)"
.br
.ti -1c
.RI "\fBAlignment\fP \fBGotohalignMultiple\fP (const bpp::VectorSequenceContainer *input, const \fBScoringModel\fP *scoreM, const int &delta, bool verbose)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MultiplePseudoCircularAlignmentFactory.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MultiplePseudoCircularAlignmentFactory::MultiplePseudoCircularAlignmentFactory ()\fC [explicit]\fP"
.PP
Definition at line 25 of file MultiplePseudoCircularAlignmentFactory.cpp.
.SS "Circal::MultiplePseudoCircularAlignmentFactory::~MultiplePseudoCircularAlignmentFactory ()\fC [virtual]\fP"
.PP
Definition at line 29 of file MultiplePseudoCircularAlignmentFactory.cpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBAlignment\fP Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple (const bpp::VectorSequenceContainer * input, const \fBScoringModel\fP * scoreM, const int & delta, bool verbose)"
.PP
Definition at line 62 of file MultiplePseudoCircularAlignmentFactory.cpp.
.PP
References Circal::Alignment::addSequence(), Circal::Output::AlignmentPrettyPrint(), Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::prettyPrint.
.SS "\fBAlignment\fP Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple (const bpp::VectorSequenceContainer * input, const \fBScoringModel\fP * scoreM, const int & delta, bool verbose)"
.PP
Definition at line 33 of file MultiplePseudoCircularAlignmentFactory.cpp.
.PP
References Circal::Alignment::addSequence(), Circal::Output::AlignmentPrettyPrint(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::AlignmentFactory::prettyPrint.
.PP
Referenced by doAllignment().

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
