.TH "Circal::CorrectedFasta" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::CorrectedFasta \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CorrectedFasta.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCorrectedFasta\fP ()"
.br
.ti -1c
.RI "virtual \fB~CorrectedFasta\fP ()"
.br
.ti -1c
.RI "void \fBappendFromStream\fP (istream &input, bpp::VectorSequenceContainer &vsc) const   throw (bpp::Exception)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file CorrectedFasta.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::CorrectedFasta::CorrectedFasta ()"
.PP
Definition at line 24 of file CorrectedFasta.cpp.
.SS "Circal::CorrectedFasta::~CorrectedFasta ()\fC [virtual]\fP"
.PP
Definition at line 28 of file CorrectedFasta.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Circal::CorrectedFasta::appendFromStream (istream & input, bpp::VectorSequenceContainer & vsc) const  throw (bpp::Exception)"
.PP
Definition at line 32 of file CorrectedFasta.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
