.TH "Circal::Alignment" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::Alignment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Alignment.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlignment\fP (const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "virtual \fB~Alignment\fP ()"
.br
.ti -1c
.RI "uint \fBget_offsetA\fP ()"
.br
.ti -1c
.RI "void \fBset_offsetA\fP (const uint &orig)"
.br
.ti -1c
.RI "uint \fBget_offsetB\fP ()"
.br
.ti -1c
.RI "void \fBset_offsetB\fP (const uint &orig)"
.br
.ti -1c
.RI "double \fBget_Score\fP ()"
.br
.ti -1c
.RI "void \fBset_Score\fP (const double &s)"
.br
.ti -1c
.RI "void \fBaddSequence\fP (const bpp::Sequence *sequence)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint \fBoffsetA\fP"
.br
.ti -1c
.RI "uint \fBoffsetB\fP"
.br
.ti -1c
.RI "double \fBScore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file Alignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::Alignment::Alignment (const bpp::Alphabet * alpha)"
.PP
Definition at line 27 of file Alignment.cpp.
.PP
References set_offsetA(), set_offsetB(), and set_Score().
.SS "Circal::Alignment::~Alignment ()\fC [virtual]\fP"
.PP
Definition at line 37 of file Alignment.cpp.
.SH "Member Function Documentation"
.PP 
.SS "uint Circal::Alignment::get_offsetA ()"
.PP
Definition at line 42 of file Alignment.cpp.
.PP
References offsetA.
.PP
Referenced by Circal::Output::TCoffeeAlignFormat().
.SS "void Circal::Alignment::set_offsetA (const uint & orig)"
.PP
Definition at line 46 of file Alignment.cpp.
.PP
Referenced by Alignment().
.SS "uint Circal::Alignment::get_offsetB ()"
.PP
Definition at line 51 of file Alignment.cpp.
.PP
References offsetB.
.PP
Referenced by Circal::Output::TCoffeeAlignFormat().
.SS "void Circal::Alignment::set_offsetB (const uint & orig)"
.PP
Definition at line 55 of file Alignment.cpp.
.PP
Referenced by Alignment().
.SS "double Circal::Alignment::get_Score (void)"
.PP
Definition at line 60 of file Alignment.cpp.
.PP
References Score.
.PP
Referenced by Circal::Output::AlignmentPrettyPrint().
.SS "void Circal::Alignment::set_Score (const double & s)"
.PP
Definition at line 65 of file Alignment.cpp.
.PP
References Score.
.PP
Referenced by Alignment().
.SS "void Circal::Alignment::addSequence (const bpp::Sequence * sequence)"
.PP
Definition at line 70 of file Alignment.cpp.
.PP
Referenced by Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), Circal::MultipleAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple(), and Circal::MultipleAlignmentFactory::NMWalignMultiple().
.SH "Member Data Documentation"
.PP 
.SS "uint \fBCircal::Alignment::offsetA\fP\fC [private]\fP"
.PP
Definition at line 38 of file Alignment.h.
.PP
Referenced by get_offsetA().
.SS "uint \fBCircal::Alignment::offsetB\fP\fC [private]\fP"
.PP
Definition at line 39 of file Alignment.h.
.PP
Referenced by get_offsetB().
.SS "double \fBCircal::Alignment::Score\fP\fC [private]\fP"
.PP
Definition at line 40 of file Alignment.h.
.PP
Referenced by get_Score(), and set_Score().

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
