.TH "Circal::MatrixHelper" 3 "21 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MatrixHelper \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MatrixHelper.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixHelper\fP ()"
.br
.ti -1c
.RI "virtual \fB~MatrixHelper\fP ()"
.br
.ti -1c
.RI "\fBScoreMatrix\fP \fBInitializeScoreMatrixDistances\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM)"
.br
.ti -1c
.RI "\fBScoreMatrix\fP \fBInitScoreMatrixWith\fP (const bpp::Sequence *A, const bpp::Sequence *B, const double &init)"
.br
.ti -1c
.RI "\fBScoreMatrix3D\fP \fBInitScoreMatrix3DWith\fP (const bpp::Sequence *A, const \fBPseudoRotatedSequence\fP *B, const int &delta, const double &init)"
.br
.ti -1c
.RI "\fBBoolMatrix\fP \fBCreateAdjacenceGraph\fP (\fBAlignment\fP *pairWiseAlignments, int biggestSequenceSize)"
.br
.ti -1c
.RI "void \fBCutRowFromTo\fP (\fBScoreMatrix\fP *D, const uint &start, const uint &end)"
.br
.ti -1c
.RI "void \fBCutColumnFromTo\fP (\fBScoreMatrix\fP *D, const uint &start, const uint &end)"
.br
.ti -1c
.RI "double \fBSearchBestPositionFrom\fP (const \fBScoreMatrix\fP *M, uint &i, uint &j, const \fBScoringModel\fP *scoreM)"
.br
.ti -1c
.RI "int \fBSearchBestInRow\fP (const \fBScoreMatrix\fP *M, const \fBScoringModel\fP *scoreM, const uint &start, const uint &row)"
.br
.ti -1c
.RI "int \fBSearchBestInRow3D\fP (const \fBScoreMatrix3D\fP *M, const \fBScoringModel\fP *scoreM, const uint &start, const uint &row, uint &k)"
.br
.ti -1c
.RI "int \fBSearchBestInColumn\fP (const \fBScoreMatrix\fP *M, const \fBScoringModel\fP *scoreM, const uint &start, const uint &column)"
.br
.ti -1c
.RI "int \fBSearchBestInColumn3D\fP (const \fBScoreMatrix3D\fP *M, const \fBScoringModel\fP *scoreM, const uint &start, const uint &column, uint &k)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file MatrixHelper.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MatrixHelper::MatrixHelper ()"
.PP
Definition at line 29 of file MatrixHelper.cpp.
.SS "Circal::MatrixHelper::~MatrixHelper ()\fC [virtual]\fP"
.PP
Definition at line 33 of file MatrixHelper.cpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBScoreMatrix\fP Circal::MatrixHelper::InitializeScoreMatrixDistances (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM)"
.PP
Definition at line 71 of file MatrixHelper.cpp.
.PP
References InitScoreMatrixWith(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::AlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::SmithWaterman().
.SS "\fBScoreMatrix\fP Circal::MatrixHelper::InitScoreMatrixWith (const bpp::Sequence * A, const bpp::Sequence * B, const double & init)"
.PP
Definition at line 100 of file MatrixHelper.cpp.
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), Circal::CircularAlignmentFactory::GotohAlignment(), Circal::AlignmentFactory::GotohAlignment(), InitializeScoreMatrixDistances(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::SmithWatermanAffin().
.SS "\fBScoreMatrix3D\fP Circal::MatrixHelper::InitScoreMatrix3DWith (const bpp::Sequence * A, const \fBPseudoRotatedSequence\fP * B, const int & delta, const double & init)"
.PP
Definition at line 108 of file MatrixHelper.cpp.
.PP
References Circal::PseudoRotatedSequence::size().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment().
.SS "\fBBoolMatrix\fP Circal::MatrixHelper::CreateAdjacenceGraph (\fBAlignment\fP * pairWiseAlignments, int biggestSequenceSize)"
.PP
Definition at line 122 of file MatrixHelper.cpp.
.SS "void Circal::MatrixHelper::CutRowFromTo (\fBScoreMatrix\fP * D, const uint & start, const uint & end)"
.PP
Definition at line 36 of file MatrixHelper.cpp.
.SS "void Circal::MatrixHelper::CutColumnFromTo (\fBScoreMatrix\fP * D, const uint & start, const uint & end)"
.PP
Definition at line 52 of file MatrixHelper.cpp.
.SS "double Circal::MatrixHelper::SearchBestPositionFrom (const \fBScoreMatrix\fP * M, uint & i, uint & j, const \fBScoringModel\fP * scoreM)"
.PP
Definition at line 227 of file MatrixHelper.cpp.
.PP
References Circal::ScoringModel::BestOfTwo(), SearchBestInColumn(), and SearchBestInRow().
.SS "int Circal::MatrixHelper::SearchBestInRow (const \fBScoreMatrix\fP * M, const \fBScoringModel\fP * scoreM, const uint & start, const uint & row)"
.PP
Definition at line 148 of file MatrixHelper.cpp.
.PP
References Circal::ScoringModel::BestOfTwo().
.PP
Referenced by SearchBestPositionFrom().
.SS "int Circal::MatrixHelper::SearchBestInRow3D (const \fBScoreMatrix3D\fP * M, const \fBScoringModel\fP * scoreM, const uint & start, const uint & row, uint & k)"
.PP
Definition at line 167 of file MatrixHelper.cpp.
.PP
References Circal::ScoringModel::BestOfTwo().
.SS "int Circal::MatrixHelper::SearchBestInColumn (const \fBScoreMatrix\fP * M, const \fBScoringModel\fP * scoreM, const uint & start, const uint & column)"
.PP
Definition at line 188 of file MatrixHelper.cpp.
.PP
References Circal::ScoringModel::BestOfTwo().
.PP
Referenced by SearchBestPositionFrom().
.SS "int Circal::MatrixHelper::SearchBestInColumn3D (const \fBScoreMatrix3D\fP * M, const \fBScoringModel\fP * scoreM, const uint & start, const uint & column, uint & k)"
.PP
Definition at line 206 of file MatrixHelper.cpp.
.PP
References Circal::ScoringModel::BestOfTwo().

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
