.TH "Circal" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlignment\fP"
.br
.ti -1c
.RI "class \fBAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBAlignmentSymbol\fP"
.br
.ti -1c
.RI "class \fBCircularAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBCorrectedFasta\fP"
.br
.ti -1c
.RI "class \fBMatrixOutofBoundsError\fP"
.br
.ti -1c
.RI "class \fBGenomeAlphabet\fP"
.br
.ti -1c
.RI "class \fBMatrixHelper\fP"
.br
.ti -1c
.RI "class \fBMultipleAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBMultipleCircularAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBMultiplePseudoCircularAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBOutput\fP"
.br
.ti -1c
.RI "class \fBPseudoCircularAlignmentFactory\fP"
.br
.ti -1c
.RI "class \fBPseudoRotatedSequence\fP"
.br
.ti -1c
.RI "class \fBRandomSequence\fP"
.br
.ti -1c
.RI "class \fBRotatedSequence\fP"
.br
.ti -1c
.RI "class \fBScoringModel\fP"
.br
.ti -1c
.RI "class \fBVertebrateMitochondrialGenomeAlphabet\fP"
.br
.ti -1c
.RI "class \fBWhitespaceFasta\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< std::vector< double > > \fBScoreMatrix\fP"
.br
.ti -1c
.RI "typedef std::valarray< std::valarray< bool > > \fBBoolMatrix\fP"
.br
.ti -1c
.RI "typedef std::vector< std::vector< std::vector< double > > > \fBScoreMatrix3D\fP"
.br
.ti -1c
.RI "typedef std::map< const std::string, \fBAlignmentSymbol\fP > \fBModelValues\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::valarray< std::valarray< bool > > \fBCircal::BoolMatrix\fP"
.PP
Definition at line 34 of file MatrixHelper.h.
.SS "typedef std::map<const std::string, \fBAlignmentSymbol\fP> \fBCircal::ModelValues\fP"
.PP
Definition at line 28 of file ScoringModel.h.
.SS "typedef std::vector< std::vector< double > > \fBCircal::ScoreMatrix\fP"
.PP
Definition at line 30 of file AlignmentFactory.h.
.SS "typedef std::vector< std::vector< std::vector< double > > > \fBCircal::ScoreMatrix3D\fP"
.PP
Definition at line 38 of file MatrixHelper.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
