.TH "Circal::AlignmentFactory" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::AlignmentFactory \- 
.SH SYNOPSIS
.br
.PP
\fC#include <AlignmentFactory.h>\fP
.PP
Inherited by \fBCircal::CircularAlignmentFactory\fP\fC [virtual]\fP, \fBCircal::MultipleAlignmentFactory\fP\fC [virtual]\fP, and \fBCircal::PseudoCircularAlignmentFactory\fP\fC [virtual]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlignmentFactory\fP ()"
.br
.ti -1c
.RI "virtual \fB~AlignmentFactory\fP ()"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBNeedlemanWunschAlignment\fP (const bpp::Sequence *inA, const bpp::Sequence *inB, const \fBScoringModel\fP *scoreM, bool verbose=false)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBGotohAlignment\fP (const bpp::Sequence *inA, const bpp::Sequence *inB, const \fBScoringModel\fP *scoreM, bool verbose=false)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBSmithWaterman\fP (const bpp::Sequence *inA, const bpp::Sequence *inB, const \fBScoringModel\fP *scoreM, bool verbose=false)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBSmithWatermanAffin\fP (const bpp::Sequence *inA, const bpp::Sequence *inB, const \fBScoringModel\fP *scoreM, bool verbose=false)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBForwardRecursionNMW\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, \fBScoreMatrix\fP *D)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBBacktrackingNMW\fP (const bpp::Sequence *outA, const bpp::Sequence *outB, const \fBScoringModel\fP *scoreM, const \fBScoreMatrix\fP *D, uint &i, uint &j)"
.br
.ti -1c
.RI "virtual void \fBForwardRecursionGotoh\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, \fBScoreMatrix\fP *D, \fBScoreMatrix\fP *P, \fBScoreMatrix\fP *Q)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBBacktrackingGotohGlocal\fP (const bpp::Sequence *outA, const bpp::Sequence *outB, const \fBScoringModel\fP *scoreM, const \fBScoreMatrix\fP *D, const \fBScoreMatrix\fP *P, const \fBScoreMatrix\fP *Q, uint &i, uint &j)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBBacktrackingGotohGlobal\fP (const bpp::Sequence *outA, const bpp::Sequence *outB, const \fBScoringModel\fP *scoreM, const \fBScoreMatrix\fP *D, const \fBScoreMatrix\fP *P, const \fBScoreMatrix\fP *Q, uint &i, uint &j)"
.br
.ti -1c
.RI "virtual double \fBForwardRecursionSmithWaterman\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, \fBScoreMatrix\fP *D, uint &i, uint &j)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBBacktrackingSmithWaterman\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, const \fBScoreMatrix\fP *D, uint &i, uint &j)"
.br
.ti -1c
.RI "virtual double \fBForwardRecursionSmithWatermanAffin\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, \fBScoreMatrix\fP *D, \fBScoreMatrix\fP *P, \fBScoreMatrix\fP *Q, uint &bi, uint &bj)"
.br
.ti -1c
.RI "virtual \fBAlignment\fP \fBBacktrackingSmithWatermanAffin\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM, const \fBScoreMatrix\fP *D, const \fBScoreMatrix\fP *P, const \fBScoreMatrix\fP *Q, uint &i, uint &j)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMatrixHelper\fP * \fBmatrix\fP"
.br
.ti -1c
.RI "\fBOutput\fP * \fBprettyPrint\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file AlignmentFactory.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::AlignmentFactory::AlignmentFactory ()"
.PP
Definition at line 29 of file AlignmentFactory.cpp.
.PP
References matrix.
.SS "Circal::AlignmentFactory::~AlignmentFactory ()\fC [virtual]\fP"
.PP
Definition at line 34 of file AlignmentFactory.cpp.
.PP
References matrix.
.SH "Member Function Documentation"
.PP 
.SS "void Circal::AlignmentFactory::ForwardRecursionNMW (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, \fBScoreMatrix\fP * D)\fC [protected, virtual]\fP"
.PP
Definition at line 358 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and NeedlemanWunschAlignment().
.SS "\fBAlignment\fP Circal::AlignmentFactory::BacktrackingNMW (const bpp::Sequence * outA, const bpp::Sequence * outB, const \fBScoringModel\fP * scoreM, const \fBScoreMatrix\fP * D, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 386 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and NeedlemanWunschAlignment().
.SS "void Circal::AlignmentFactory::ForwardRecursionGotoh (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, \fBScoreMatrix\fP * D, \fBScoreMatrix\fP * P, \fBScoreMatrix\fP * Q)\fC [protected, virtual]\fP"
.PP
Definition at line 38 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), and GotohAlignment().
.SS "\fBAlignment\fP Circal::AlignmentFactory::BacktrackingGotohGlocal (const bpp::Sequence * outA, const bpp::Sequence * outB, const \fBScoringModel\fP * scoreM, const \fBScoreMatrix\fP * D, const \fBScoreMatrix\fP * P, const \fBScoreMatrix\fP * Q, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 81 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.SS "\fBAlignment\fP Circal::AlignmentFactory::BacktrackingGotohGlobal (const bpp::Sequence * outA, const bpp::Sequence * outB, const \fBScoringModel\fP * scoreM, const \fBScoreMatrix\fP * D, const \fBScoreMatrix\fP * P, const \fBScoreMatrix\fP * Q, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 213 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), and GotohAlignment().
.SS "double Circal::AlignmentFactory::ForwardRecursionSmithWaterman (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, \fBScoreMatrix\fP * D, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 489 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and SmithWaterman().
.SS "\fBAlignment\fP Circal::AlignmentFactory::BacktrackingSmithWaterman (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, const \fBScoreMatrix\fP * D, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 534 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and SmithWaterman().
.SS "double Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, \fBScoreMatrix\fP * D, \fBScoreMatrix\fP * P, \fBScoreMatrix\fP * Q, uint & bi, uint & bj)\fC [protected, virtual]\fP"
.PP
Definition at line 622 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and SmithWatermanAffin().
.SS "\fBAlignment\fP Circal::AlignmentFactory::BacktrackingSmithWatermanAffin (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM, const \fBScoreMatrix\fP * D, const \fBScoreMatrix\fP * P, const \fBScoreMatrix\fP * Q, uint & i, uint & j)\fC [protected, virtual]\fP"
.PP
Definition at line 679 of file AlignmentFactory.cpp.
.PP
References Circal::ScoringModel::BestOfTwo(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
.PP
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and SmithWatermanAffin().
.SS "\fBAlignment\fP Circal::AlignmentFactory::NeedlemanWunschAlignment (const bpp::Sequence * inA, const bpp::Sequence * inB, const \fBScoringModel\fP * scoreM, bool verbose = \fCfalse\fP)\fC [virtual]\fP"
.PP
Definition at line 805 of file AlignmentFactory.cpp.
.PP
References BacktrackingNMW(), ForwardRecursionNMW(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), and matrix.
.PP
Referenced by Circal::MultipleAlignmentFactory::NMWalignMultiple().
.SS "\fBAlignment\fP Circal::AlignmentFactory::GotohAlignment (const bpp::Sequence * inA, const bpp::Sequence * inB, const \fBScoringModel\fP * scoreM, bool verbose = \fCfalse\fP)\fC [virtual]\fP"
.PP
Definition at line 822 of file AlignmentFactory.cpp.
.PP
References BacktrackingGotohGlobal(), ForwardRecursionGotoh(), Circal::MatrixHelper::InitScoreMatrixWith(), and matrix.
.PP
Referenced by Circal::MultipleAlignmentFactory::GotohalignMultiple().
.SS "\fBAlignment\fP Circal::AlignmentFactory::SmithWaterman (const bpp::Sequence * inA, const bpp::Sequence * inB, const \fBScoringModel\fP * scoreM, bool verbose = \fCfalse\fP)\fC [virtual]\fP"
.PP
Definition at line 839 of file AlignmentFactory.cpp.
.PP
References BacktrackingSmithWaterman(), ForwardRecursionSmithWaterman(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), and matrix.
.SS "\fBAlignment\fP Circal::AlignmentFactory::SmithWatermanAffin (const bpp::Sequence * inA, const bpp::Sequence * inB, const \fBScoringModel\fP * scoreM, bool verbose = \fCfalse\fP)\fC [virtual]\fP"
.PP
Definition at line 853 of file AlignmentFactory.cpp.
.PP
References BacktrackingSmithWatermanAffin(), ForwardRecursionSmithWatermanAffin(), Circal::MatrixHelper::InitScoreMatrixWith(), and matrix.
.SH "Member Data Documentation"
.PP 
.SS "\fBMatrixHelper\fP* \fBCircal::AlignmentFactory::matrix\fP\fC [protected]\fP"
.PP
Definition at line 37 of file AlignmentFactory.h.
.PP
Referenced by AlignmentFactory(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), Circal::CircularAlignmentFactory::GotohAlignment(), GotohAlignment(), Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), NeedlemanWunschAlignment(), SmithWaterman(), SmithWatermanAffin(), and ~AlignmentFactory().
.SS "\fBOutput\fP* \fBCircal::AlignmentFactory::prettyPrint\fP\fC [protected]\fP"
.PP
Definition at line 38 of file AlignmentFactory.h.
.PP
Referenced by Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), and Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple().

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
