.TH "Circal::MultipleMetaCircularAlignment" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MultipleMetaCircularAlignment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MultipleMetaCircularAlignment.h>\fP
.PP
Inherits \fBCircal::MetaCircularAlignment\fP, and \fBCircal::MultipleAlignment\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultipleMetaCircularAlignment\fP (const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "\fBMultipleMetaCircularAlignment\fP (const VectorSequenceContainer *input, const \fBScoringModel\fP *scoreM)"
.br
.ti -1c
.RI "virtual \fB~MultipleMetaCircularAlignment\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MultipleMetaCircularAlignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MultipleMetaCircularAlignment::MultipleMetaCircularAlignment (const bpp::Alphabet * alpha)\fC [explicit]\fP"
.PP
Definition at line 24 of file MultipleMetaCircularAlignment.cpp.
.SS "Circal::MultipleMetaCircularAlignment::MultipleMetaCircularAlignment (const VectorSequenceContainer * input, const \fBScoringModel\fP * scoreM)"
.PP
Definition at line 31 of file MultipleMetaCircularAlignment.cpp.
.PP
References Circal::MultipleAlignment::GotohalignMultiple().
.SS "Circal::MultipleMetaCircularAlignment::~MultipleMetaCircularAlignment ()\fC [virtual]\fP"
.PP
Definition at line 44 of file MultipleMetaCircularAlignment.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
