.TH "Circal::MultipleCircularAlignment" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MultipleCircularAlignment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MultipleCircularAlignment.h>\fP
.PP
Inherits \fBCircal::CircularAlignment\fP, and \fBCircal::MultipleAlignment\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultipleCircularAlignment\fP (const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "\fBMultipleCircularAlignment\fP (const VectorSequenceContainer *input, const \fBScoringModel\fP *scoreM)"
.br
.ti -1c
.RI "virtual \fB~MultipleCircularAlignment\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file MultipleCircularAlignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MultipleCircularAlignment::MultipleCircularAlignment (const bpp::Alphabet * alpha)\fC [explicit]\fP"
.PP
Definition at line 26 of file MultipleCircularAlignment.cpp.
.SS "Circal::MultipleCircularAlignment::MultipleCircularAlignment (const VectorSequenceContainer * input, const \fBScoringModel\fP * scoreM)"
.PP
Definition at line 33 of file MultipleCircularAlignment.cpp.
.PP
References Circal::MultipleAlignment::GotohalignMultiple().
.SS "Circal::MultipleCircularAlignment::~MultipleCircularAlignment ()\fC [virtual]\fP"
.PP
Definition at line 45 of file MultipleCircularAlignment.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
