.TH "Circal::MatrixOutofBoundsError" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MatrixOutofBoundsError \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ErrorClasses.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrixOutofBoundsError\fP (const uint &start, const uint &end, const uint &size)"
.br
.ti -1c
.RI "virtual \fB~MatrixOutofBoundsError\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file ErrorClasses.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MatrixOutofBoundsError::MatrixOutofBoundsError (const uint & start, const uint & end, const uint & size)"
.PP
Definition at line 27 of file ErrorClasses.cpp.
.SS "Circal::MatrixOutofBoundsError::~MatrixOutofBoundsError ()\fC [virtual]\fP"
.PP
Definition at line 34 of file ErrorClasses.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
