.TH "Circal::Alignment" 3 "20 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::Alignment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Alignment.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlignment\fP (const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "\fBAlignment\fP ()"
.br
.ti -1c
.RI "virtual \fB~Alignment\fP ()"
.br
.ti -1c
.RI "uint \fBget_origSize\fP () const "
.br
.ti -1c
.RI "double \fBget_Score\fP () const "
.br
.ti -1c
.RI "void \fBset_Score\fP (const double &s)"
.br
.ti -1c
.RI "void \fBset_origSize\fP (const uint &orig)"
.br
.ti -1c
.RI "void \fBaddSequence\fP (const bpp::Sequence &sequence, bool checkNames)  throw (bpp::Exception)"
.br
.ti -1c
.RI "void \fBaddSequence\fP (const bpp::Sequence &sequence)  throw (bpp::Exception)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "uint \fBorigSize\fP"
.br
.ti -1c
.RI "double \fBScore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file Alignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::Alignment::Alignment (const bpp::Alphabet * alpha)"
.PP
Definition at line 27 of file Alignment.cpp.
.PP
References set_Score().
.SS "Circal::Alignment::Alignment ()"
.PP
.SS "Circal::Alignment::~Alignment ()\fC [virtual]\fP"
.PP
Definition at line 35 of file Alignment.cpp.
.SH "Member Function Documentation"
.PP 
.SS "uint Circal::Alignment::get_origSize () const"
.PP
Definition at line 39 of file Alignment.cpp.
.PP
References origSize.
.PP
Referenced by Circal::Output::TCoffeeLibFormat().
.SS "double Circal::Alignment::get_Score (void) const"
.PP
Definition at line 48 of file Alignment.cpp.
.PP
References Score.
.PP
Referenced by Circal::Output::AlignmentPrettyPrint(), Circal::CircularAlignmentFactory::GotohAlignment(), main(), and Circal::CircularAlignmentFactory::NeedlemanWunschAlignment().
.SS "void Circal::Alignment::set_Score (const double & s)"
.PP
Definition at line 53 of file Alignment.cpp.
.PP
References Score.
.PP
Referenced by Alignment(), Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::PseudoCircularAlignmentFactory::BacktrackingGotohLocal(), Circal::AlignmentFactory::BacktrackingGotohLocal(), Circal::PseudoCircularAlignmentFactory::BacktrackingNMW(), and Circal::AlignmentFactory::BacktrackingNMW().
.SS "void Circal::Alignment::set_origSize (const uint & orig)"
.PP
Definition at line 43 of file Alignment.cpp.
.PP
References origSize.
.SS "void Circal::Alignment::addSequence (const bpp::Sequence & sequence, bool checkNames)  throw (bpp::Exception)"
.PP
Definition at line 58 of file Alignment.cpp.
.PP
Referenced by addSequence(), Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::PseudoCircularAlignmentFactory::BacktrackingGotohLocal(), Circal::AlignmentFactory::BacktrackingGotohLocal(), Circal::PseudoCircularAlignmentFactory::BacktrackingNMW(), and Circal::AlignmentFactory::BacktrackingNMW().
.SS "void Circal::Alignment::addSequence (const bpp::Sequence & sequence)  throw (bpp::Exception)"
.PP
Definition at line 64 of file Alignment.cpp.
.PP
References addSequence().
.SH "Member Data Documentation"
.PP 
.SS "uint \fBCircal::Alignment::origSize\fP\fC [private]\fP"
.PP
Definition at line 38 of file Alignment.h.
.PP
Referenced by get_origSize(), and set_origSize().
.SS "double \fBCircal::Alignment::Score\fP\fC [private]\fP"
.PP
Definition at line 39 of file Alignment.h.
.PP
Referenced by get_Score(), and set_Score().

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
