.TH "Circal::MetaCircularAlignment" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::MetaCircularAlignment \- 
.SH SYNOPSIS
.br
.PP
\fC#include <MetaCircularAlignment.h>\fP
.PP
Inherits \fBCircal::CircularAlignment\fP.
.PP
Inherited by \fBCircal::MultipleMetaCircularAlignment\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetaCircularAlignment\fP (const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "virtual \fB~MetaCircularAlignment\fP ()"
.br
.ti -1c
.RI "\fBAlignment\fP * \fBGotohAlignment\fP (const bpp::Sequence *A, const bpp::Sequence *B, const \fBScoringModel\fP *scoreM)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file MetaCircularAlignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::MetaCircularAlignment::MetaCircularAlignment (const bpp::Alphabet * alpha)"
.PP
Definition at line 28 of file MetaCircularAlignment.cpp.
.SS "Circal::MetaCircularAlignment::~MetaCircularAlignment ()\fC [virtual]\fP"
.PP
Definition at line 34 of file MetaCircularAlignment.cpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBAlignment\fP * Circal::MetaCircularAlignment::GotohAlignment (const bpp::Sequence * A, const bpp::Sequence * B, const \fBScoringModel\fP * scoreM)\fC [virtual]\fP"
.PP
Reimplemented from \fBCircal::CircularAlignment\fP.
.PP
Definition at line 38 of file MetaCircularAlignment.cpp.
.PP
References Circal::Alignment::BacktrackingGotoh(), Circal::Alignment::ForwardRecursionGotoh(), Circal::MatrixHelper::InitScoreMatrixWith(), and Circal::Alignment::matrix.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
