.TH "Circal::WhitespaceFasta" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::WhitespaceFasta \- 
.SH SYNOPSIS
.br
.PP
\fC#include <WhitespaceFasta.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWhitespaceFasta\fP ()"
.br
.ti -1c
.RI "virtual \fB~WhitespaceFasta\fP ()"
.br
.ti -1c
.RI "void \fBappendFromStream\fP (istream &input, bpp::VectorSequenceContainer &vsc) const   throw (bpp::Exception)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file WhitespaceFasta.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::WhitespaceFasta::WhitespaceFasta ()"
.PP
Definition at line 25 of file WhitespaceFasta.cpp.
.SS "Circal::WhitespaceFasta::~WhitespaceFasta ()\fC [virtual]\fP"
.PP
Definition at line 29 of file WhitespaceFasta.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Circal::WhitespaceFasta::appendFromStream (istream & input, bpp::VectorSequenceContainer & vsc) const  throw (bpp::Exception)"
.PP
Definition at line 32 of file WhitespaceFasta.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
