.TH "Circal::ExtendedFasta" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::ExtendedFasta \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ExtendedFasta.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExtendedFasta\fP ()"
.br
.ti -1c
.RI "virtual \fB~ExtendedFasta\fP ()"
.br
.ti -1c
.RI "void \fBappendFromStream\fP (istream &input, bpp::VectorSequenceContainer &vsc) const   throw (bpp::Exception)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file ExtendedFasta.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::ExtendedFasta::ExtendedFasta ()"
.PP
Definition at line 24 of file ExtendedFasta.cpp.
.SS "Circal::ExtendedFasta::~ExtendedFasta ()\fC [virtual]\fP"
.PP
Definition at line 28 of file ExtendedFasta.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Circal::ExtendedFasta::appendFromStream (istream & input, bpp::VectorSequenceContainer & vsc) const  throw (bpp::Exception)"
.PP
Definition at line 32 of file ExtendedFasta.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
