.TH "Circal::RandomSequence" 3 "21 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circal::RandomSequence \- 
.SH SYNOPSIS
.br
.PP
\fC#include <RandomSequence.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomSequence\fP (const uint &size, const bpp::Alphabet *alpha)"
.br
.ti -1c
.RI "virtual \fB~RandomSequence\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file RandomSequence.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circal::RandomSequence::RandomSequence (const uint & size, const bpp::Alphabet * alpha)"
.PP
Definition at line 6 of file RandomSequence.cpp.
.SS "Circal::RandomSequence::~RandomSequence ()\fC [virtual]\fP"
.PP
Definition at line 18 of file RandomSequence.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
