.TH "Uni/workspace/CircalPP/src/main.cpp" 3 "20 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uni/workspace/CircalPP/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MultipleCircularAlignmentFactory.h'\fP
.br
\fC#include 'MultiplePseudoCircularAlignmentFactory.h'\fP
.br
\fC#include 'ScoringModel.h'\fP
.br
\fC#include 'ExtendedFasta.h'\fP
.br
\fC#include 'Output.h'\fP
.br
\fC#include 'RandomSequence.h'\fP
.br
\fC#include 'VertebrateMitochondrialGenomeAlphabet.h'\fP
.br
\fC#include <Seq/alphabets>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int args, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int args, char * argv[])"
.PP
Definition at line 36 of file main.cpp.
.PP
References Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::get_Score(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::CircularAlignmentFactory::GotohAlignment().
.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
