.TH "Uni/workspace/CircalPP/src/MatrixHelper.h" 3 "8 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uni/workspace/CircalPP/src/MatrixHelper.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <valarray>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbpp\fP"
.br
.ti -1c
.RI "namespace \fBCircal\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircal::MatrixHelper\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::valarray< std::valarray< bool > > \fBCircal::BoolMatrix\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
