.TH "Uni/workspace/CircalPP/src/ScoringModel.h" 3 "24 Feb 2008" "Version 0.1" "CircalPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Uni/workspace/CircalPP/src/ScoringModel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCircal\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircal::ScoringModel\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< const std::string, AlignmentSymbol > \fBCircal::ModelValues\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CircalPP from the source code.
