CircalPP: github/CircalPP/src/CircalPP.cpp File Reference
CircalPP.cpp File Reference
#include "MultipleCircularAlignmentFactory.h"
#include "MultiplePseudoCircularAlignmentFactory.h"
#include "ScoringModel.h"
#include "CorrectedFasta.h"
#include "WhitespaceFasta.h"
#include "Output.h"
#include "RandomSequence.h"
#include "VertebrateMitochondrialGenomeAlphabet.h"
#include <Bpp/Seq/Alphabet/DNA.h>
#include <Bpp/Seq/Alphabet/RNA.h>
#include <Bpp/Seq/Io/Fasta.h>
#include <iostream>
#include <fstream>
#include <sstream>
Functions
std::string usage ()
void doAllignment (const bpp::Alphabet *alpha, const std::string &seqFilename, Circal::ScoringModel &scoreM, const std::string &outFilename, const std::string &resultFilename, bool outF, bool resultF, int &delta, bool verbose, bool stepWise, bool multipl, bool brute, bool statistic, uint &size)
int main (int args, char *argv[])
Function Documentation
void doAllignment (const bpp::Alphabet * alpha, const std::string & seqFilename, Circal::ScoringModel & scoreM, const std::string & outFilename, const std::string & resultFilename, bool outF, bool resultF, int & delta, bool verbose, bool stepWise, bool multipl, bool brute, bool statistic, uint & size)
Definition at line 67 of file CircalPP.cpp.
References Circal::Alignment::get_Score(), Circal::Alignment::getSequence(), Circal::CircularAlignmentFactory::GotohAlignment(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), Circal::MultipleAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), Circal::Output::TCoffeeAlignFormat(), Circal::Output::TCoffeeLibFooter(), Circal::Output::TCoffeeLibFormat(), and Circal::Output::TCoffeeLibHeader().
Referenced by main().
int main (int args, char * argv[])
Definition at line 341 of file CircalPP.cpp.
References doAllignment(), and usage().
std::string usage ()
Definition at line 39 of file CircalPP.cpp.
Referenced by main().