CircalPP: Circal::Alignment Class Reference
Circal::Alignment Class Reference
#include <Alignment.h>
Public Member Functions
Alignment (const bpp::Alphabet *alpha)
virtual ~Alignment ()
uint get_offsetA ()
void set_offsetA (const uint &orig)
uint get_offsetB ()
void set_offsetB (const uint &orig)
double get_Score ()
void set_Score (const double &s)
void addSequence (const SequenceProxy sequence)
void deleteSequence (const std::string &name) throw (bpp::SequenceNotFoundException)
void deleteSequence (unsigned int sequenceIndex) throw (bpp::IndexOutOfBoundsException)
std::string toString (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException)
std::string toString (const std::string &name) const throw (bpp::SequenceNotFoundException)
int & operator() (unsigned int sequenceIndex, unsigned int elementIndex)
const int & operator() (unsigned int sequenceIndex, unsigned int elementIndex) const
int & operator() (const std::string &sequenceName, unsigned int elementIndex)
const int & operator() (const std::string &sequenceName, unsigned int elementIndex) const
int & valueAt (unsigned int sequenceIndex, unsigned int elementIndex) throw (bpp::IndexOutOfBoundsException)
const int & valueAt (unsigned int sequenceIndex, unsigned int elementIndex) const throw (bpp::IndexOutOfBoundsException)
int & valueAt (const std::string &sequenceName, unsigned int elementIndex) throw (bpp::SequenceNotFoundException, bpp::IndexOutOfBoundsException)
const int & valueAt (const std::string &sequenceName, unsigned int elementIndex) const throw (bpp::SequenceNotFoundException, bpp::IndexOutOfBoundsException)
const bpp::Sequence & getSequence (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException)
const bpp::Sequence & getSequence (const std::string &name) const throw (bpp::SequenceNotFoundException)
const bpp::Comments & getComments (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException)
const bpp::Comments & getComments (const std::string &name) const throw (bpp::SequenceNotFoundException)
const std::vector< int > & getContent (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException)
const std::vector< int > & getContent (const std::string &name) const throw (bpp::SequenceNotFoundException)
void setSequencesNames (const std::vector< std::string > &names, bool checkNames) throw (bpp::Exception)
std::vector< std::string > getSequencesNames () const
unsigned int getNumberOfSequences () const
void setComments (const std::string &name, const bpp::Comments &comments) throw (bpp::SequenceNotFoundException)
void setComments (unsigned int sequenceIndex, const bpp::Comments &comments) throw (bpp::IndexOutOfBoundsException)
bpp::Sequence * removeSequence (const std::string &name) throw (bpp::SequenceNotFoundException)
bpp::Sequence * removeSequence (unsigned int sequenceIndex) throw (bpp::IndexOutOfBoundsException)
void deleteGeneralComments ()
void setGeneralComments (const bpp::Comments &comments)
const bpp::Comments & getGeneralComments () const
const std::string & getName (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException)
const bpp::Alphabet * getAlphabet () const
unsigned int getSequencePosition (const std::string &name) const throw (bpp::SequenceNotFoundException)
bool hasSequence (const std::string &name) const
Private Attributes
uint offsetA
uint offsetB
double Score
Detailed Description
Definition at line 39 of file Alignment.h.
Constructor & Destructor Documentation
Circal::Alignment::Alignment (const bpp::Alphabet * alpha)
Definition at line 28 of file Alignment.cpp.
Circal::Alignment::~Alignment () virtual
Definition at line 34 of file Alignment.cpp.
Member Function Documentation
void Circal::Alignment::addSequence (const SequenceProxy sequence)
Definition at line 67 of file Alignment.cpp.
Referenced by Circal::MultipleAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple(), Circal::MultipleAlignmentFactory::NMWalignMultiple(), and Circal::Output::TCoffeeLibFormat().
void Circal::Alignment::deleteGeneralComments () inline
Definition at line 219 of file Alignment.h.
void Circal::Alignment::deleteSequence (const std::string & name) throw (bpp::SequenceNotFoundException) inline
Definition at line 62 of file Alignment.h.
void Circal::Alignment::deleteSequence (unsigned int sequenceIndex) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 68 of file Alignment.h.
uint Circal::Alignment::get_offsetA ()
Definition at line 39 of file Alignment.cpp.
References offsetA.
Referenced by Circal::Output::TCoffeeAlignFormat().
uint Circal::Alignment::get_offsetB ()
Definition at line 48 of file Alignment.cpp.
References offsetB.
Referenced by Circal::Output::TCoffeeAlignFormat().
double Circal::Alignment::get_Score (void)
Definition at line 57 of file Alignment.cpp.
References Score.
Referenced by Circal::Output::AlignmentPrettyPrint(), and doAllignment().
const bpp::Alphabet* Circal::Alignment::getAlphabet () const inline
Definition at line 240 of file Alignment.h.
Referenced by Circal::Output::TCoffeeLibFormat().
const bpp::Comments& Circal::Alignment::getComments (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 155 of file Alignment.h.
const bpp::Comments& Circal::Alignment::getComments (const std::string & name) const throw (bpp::SequenceNotFoundException) inline
Definition at line 161 of file Alignment.h.
const std::vector<int>& Circal::Alignment::getContent (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 167 of file Alignment.h.
const std::vector<int>& Circal::Alignment::getContent (const std::string & name) const throw (bpp::SequenceNotFoundException) inline
Definition at line 173 of file Alignment.h.
const bpp::Comments& Circal::Alignment::getGeneralComments () const inline
Definition at line 229 of file Alignment.h.
const std::string& Circal::Alignment::getName (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 234 of file Alignment.h.
unsigned int Circal::Alignment::getNumberOfSequences () const inline
Definition at line 190 of file Alignment.h.
Referenced by Circal::Output::AlignmentPrettyPrint(), Circal::MatrixHelper::CreateAdjacenceGraph(), and Circal::Output::TCoffeeLibFormat().
const bpp::Sequence& Circal::Alignment::getSequence (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 143 of file Alignment.h.
Referenced by Circal::Output::AlignmentPrettyPrint(), Circal::MatrixHelper::CreateAdjacenceGraph(), doAllignment(), Circal::MultipleAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple(), Circal::MultipleAlignmentFactory::NMWalignMultiple(), Circal::Output::TCoffeeAlignFormat(), and Circal::Output::TCoffeeLibFormat().
const bpp::Sequence& Circal::Alignment::getSequence (const std::string & name) const throw (bpp::SequenceNotFoundException) inline
Definition at line 149 of file Alignment.h.
unsigned int Circal::Alignment::getSequencePosition (const std::string & name) const throw (bpp::SequenceNotFoundException) inline
Definition at line 245 of file Alignment.h.
std::vector<std::string> Circal::Alignment::getSequencesNames () const inline
Definition at line 185 of file Alignment.h.
bool Circal::Alignment::hasSequence (const std::string & name) const inline
Definition at line 251 of file Alignment.h.
int& Circal::Alignment::operator() (unsigned int sequenceIndex, unsigned int elementIndex) inline
Definition at line 86 of file Alignment.h.
const int& Circal::Alignment::operator() (unsigned int sequenceIndex, unsigned int elementIndex) const inline
Definition at line 92 of file Alignment.h.
int& Circal::Alignment::operator() (const std::string & sequenceName, unsigned int elementIndex) inline
Definition at line 99 of file Alignment.h.
const int& Circal::Alignment::operator() (const std::string & sequenceName, unsigned int elementIndex) const inline
Definition at line 107 of file Alignment.h.
bpp::Sequence* Circal::Alignment::removeSequence (const std::string & name) throw (bpp::SequenceNotFoundException) inline
Definition at line 207 of file Alignment.h.
bpp::Sequence* Circal::Alignment::removeSequence (unsigned int sequenceIndex) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 213 of file Alignment.h.
void Circal::Alignment::set_offsetA (const uint & orig)
Definition at line 43 of file Alignment.cpp.
References offsetA.
void Circal::Alignment::set_offsetB (const uint & orig)
Definition at line 52 of file Alignment.cpp.
References offsetB.
void Circal::Alignment::set_Score (const double & s)
Definition at line 62 of file Alignment.cpp.
References Score.
void Circal::Alignment::setComments (const std::string & name, const bpp::Comments & comments) throw (bpp::SequenceNotFoundException) inline
Definition at line 195 of file Alignment.h.
void Circal::Alignment::setComments (unsigned int sequenceIndex, const bpp::Comments & comments) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 201 of file Alignment.h.
void Circal::Alignment::setGeneralComments (const bpp::Comments & comments) inline
Definition at line 224 of file Alignment.h.
void Circal::Alignment::setSequencesNames (const std::vector< std::string > & names, bool checkNames) throw (bpp::Exception) inline
Definition at line 179 of file Alignment.h.
std::string Circal::Alignment::toString (unsigned int sequenceIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 74 of file Alignment.h.
std::string Circal::Alignment::toString (const std::string & name) const throw (bpp::SequenceNotFoundException) inline
Definition at line 80 of file Alignment.h.
int& Circal::Alignment::valueAt (unsigned int sequenceIndex, unsigned int elementIndex) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 114 of file Alignment.h.
const int& Circal::Alignment::valueAt (unsigned int sequenceIndex, unsigned int elementIndex) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 121 of file Alignment.h.
int& Circal::Alignment::valueAt (const std::string & sequenceName, unsigned int elementIndex) throw (bpp::SequenceNotFoundException, bpp::IndexOutOfBoundsException) inline
Definition at line 129 of file Alignment.h.
const int& Circal::Alignment::valueAt (const std::string & sequenceName, unsigned int elementIndex) const throw (bpp::SequenceNotFoundException, bpp::IndexOutOfBoundsException) inline
Definition at line 135 of file Alignment.h.
Member Data Documentation
uint Circal::Alignment::offsetA private
Definition at line 41 of file Alignment.h.
Referenced by get_offsetA(), and set_offsetA().
uint Circal::Alignment::offsetB private
Definition at line 42 of file Alignment.h.
Referenced by get_offsetB(), and set_offsetB().
double Circal::Alignment::Score private
Definition at line 43 of file Alignment.h.
Referenced by get_Score(), and set_Score().
The documentation for this class was generated from the following files:
github/CircalPP/include/Alignment.h
github/CircalPP/src/Alignment.cpp