CircalPP: Circal::RotatedSequence Class Reference
Circal::RotatedSequence Class Reference
#include <RotatedSequence.h>
Public Member Functions
RotatedSequence (const SequenceProxy a, const uint &i)
virtual ~RotatedSequence ()
virtual int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as an int.
virtual std::string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as a character.
std::string toString () const
Convert the list as a string.
Public Member Functions inherited from Circal::SequenceProxy
SequenceProxy (const std::string &name, const std::vector< int > &sequence, const bpp::Alphabet *alpha) throw (bpp::BadIntException)
SequenceProxy (const bpp::Sequence &sequence)
SequenceProxy (const std::string &name, const std::string &sequence, const bpp::Alphabet *alpha)
virtual ~SequenceProxy ()
void shuffle ()
void deleteElement (unsigned int pos) throw (bpp::IndexOutOfBoundsException)
void deleteElements (unsigned int pos, unsigned int len) throw (bpp::IndexOutOfBoundsException)
const bpp::Alphabet * getAlphabet () const
void setContent (const std::vector< int > &list) throw (bpp::BadIntException)
const std::vector< int > & getContent () const
void setElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void setElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
void addElement (const std::string &c) throw (bpp::BadCharException)
void addElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void addElement (int v) throw (bpp::BadIntException)
void addElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
unsigned int size () const
std::string toString () const
std::string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
const int & operator[] (unsigned int i) const
int & operator[] (unsigned int i)
int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Private Attributes
uint offset
Detailed Description
Definition at line 32 of file RotatedSequence.h.
Constructor & Destructor Documentation
Circal::RotatedSequence::RotatedSequence (const SequenceProxy a, const uint & i)
Definition at line 26 of file RotatedSequence.cpp.
Circal::RotatedSequence::~RotatedSequence () virtual
Definition at line 31 of file RotatedSequence.cpp.
Member Function Documentation
std::string Circal::RotatedSequence::getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) virtual
Get the element at position 'pos' as a character.
Parameters
pos The position of the character to retrieve.
Reimplemented in Circal::PseudoRotatedSequence.
Definition at line 45 of file RotatedSequence.cpp.
int Circal::RotatedSequence::getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) virtual
Get the element at position 'pos' as an int.
Parameters
pos The position of the character to retrieve.
Reimplemented in Circal::PseudoRotatedSequence.
Definition at line 35 of file RotatedSequence.cpp.
Referenced by toString().
std::string Circal::RotatedSequence::toString () const
Convert the list as a string.
This method is useful for dumping a list to a file or to the screen for display.
Returns
The whole list as a string.
Definition at line 74 of file RotatedSequence.cpp.
References Circal::SequenceProxy::getAlphabet(), getValue(), and Circal::SequenceProxy::size().
Member Data Documentation
uint Circal::RotatedSequence::offset private
Definition at line 34 of file RotatedSequence.h.
The documentation for this class was generated from the following files:
github/CircalPP/include/RotatedSequence.h
github/CircalPP/src/RotatedSequence.cpp