CircalPP: Circal::SequenceProxy Class Reference
Circal::SequenceProxy Class Reference
#include <SequenceProxy.h>
Public Member Functions
SequenceProxy (const std::string &name, const std::vector< int > &sequence, const bpp::Alphabet *alpha) throw (bpp::BadIntException)
SequenceProxy (const bpp::Sequence &sequence)
SequenceProxy (const std::string &name, const std::string &sequence, const bpp::Alphabet *alpha)
virtual ~SequenceProxy ()
void shuffle ()
void deleteElement (unsigned int pos) throw (bpp::IndexOutOfBoundsException)
void deleteElements (unsigned int pos, unsigned int len) throw (bpp::IndexOutOfBoundsException)
const bpp::Alphabet * getAlphabet () const
void setContent (const std::vector< int > &list) throw (bpp::BadIntException)
const std::vector< int > & getContent () const
void setElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void setElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
void addElement (const std::string &c) throw (bpp::BadCharException)
void addElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void addElement (int v) throw (bpp::BadIntException)
void addElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
unsigned int size () const
std::string toString () const
std::string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
const int & operator[] (unsigned int i) const
int & operator[] (unsigned int i)
int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Detailed Description
Definition at line 27 of file SequenceProxy.h.
Constructor & Destructor Documentation
Circal::SequenceProxy::SequenceProxy (const std::string & name, const std::vector< int > & sequence, const bpp::Alphabet * alpha) throw (bpp::BadIntException)
Definition at line 24 of file SequenceProxy.cpp.
Circal::SequenceProxy::SequenceProxy (const bpp::Sequence & sequence)
Definition at line 32 of file SequenceProxy.cpp.
Circal::SequenceProxy::SequenceProxy (const std::string & name, const std::string & sequence, const bpp::Alphabet * alpha)
Definition at line 38 of file SequenceProxy.cpp.
Circal::SequenceProxy::~SequenceProxy () virtual
Definition at line 44 of file SequenceProxy.cpp.
Member Function Documentation
void Circal::SequenceProxy::addElement (const std::string & c) throw (bpp::BadCharException) inline
Definition at line 82 of file SequenceProxy.h.
void Circal::SequenceProxy::addElement (unsigned int pos, const std::string & c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException) inline
Definition at line 88 of file SequenceProxy.h.
void Circal::SequenceProxy::addElement (int v) throw (bpp::BadIntException) inline
Definition at line 94 of file SequenceProxy.h.
void Circal::SequenceProxy::addElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException) inline
Definition at line 100 of file SequenceProxy.h.
void Circal::SequenceProxy::deleteElement (unsigned int pos) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 43 of file SequenceProxy.h.
void Circal::SequenceProxy::deleteElements (unsigned int pos, unsigned int len) throw (bpp::IndexOutOfBoundsException) inline
Definition at line 49 of file SequenceProxy.h.
const bpp::Alphabet* Circal::SequenceProxy::getAlphabet () const inline
Definition at line 55 of file SequenceProxy.h.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), and Circal::RotatedSequence::toString().
std::string Circal::SequenceProxy::getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 116 of file SequenceProxy.h.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), Circal::Output::ScoreMatrixPrettyPrint(), and Circal::Output::SequencePrettyPrint().
const std::vector<int>& Circal::SequenceProxy::getContent () const inline
Definition at line 65 of file SequenceProxy.h.
int Circal::SequenceProxy::getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) inline
Definition at line 132 of file SequenceProxy.h.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), and Circal::AlignmentFactory::BacktrackingSmithWatermanAffin().
const int& Circal::SequenceProxy::operator[] (unsigned int i) const inline
Definition at line 122 of file SequenceProxy.h.
int& Circal::SequenceProxy::operator[] (unsigned int i) inline
Definition at line 127 of file SequenceProxy.h.
void Circal::SequenceProxy::setContent (const std::vector< int > & list) throw (bpp::BadIntException) inline
Definition at line 60 of file SequenceProxy.h.
void Circal::SequenceProxy::setElement (unsigned int pos, const std::string & c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException) inline
Definition at line 70 of file SequenceProxy.h.
void Circal::SequenceProxy::setElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException) inline
Definition at line 76 of file SequenceProxy.h.
void Circal::SequenceProxy::shuffle () inline
Definition at line 38 of file SequenceProxy.h.
unsigned int Circal::SequenceProxy::size () const inline
Definition at line 106 of file SequenceProxy.h.
Referenced by Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::CircularAlignmentFactory::GotohAlignment(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), Circal::MatrixHelper::InitScoreMatrix3DWith(), Circal::MatrixHelper::InitScoreMatrixWith(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::Output::ScoreMatrixPrettyPrint(), Circal::Output::SequencePrettyPrint(), and Circal::RotatedSequence::toString().
std::string Circal::SequenceProxy::toString () const inline
Definition at line 111 of file SequenceProxy.h.
The documentation for this class was generated from the following files:
github/CircalPP/include/SequenceProxy.h
github/CircalPP/src/SequenceProxy.cpp