CircalPP: Circal::MetaCircularAlignment Class Reference
Circal::MetaCircularAlignment
Circal::MetaCircularAlignment Class Reference
#include <MetaCircularAlignment.h>
Public Member Functions
MetaCircularAlignment (const bpp::Alphabet *alpha)
virtual ~MetaCircularAlignment ()
Alignment * GotohAlignment (const bpp::Sequence *A, const bpp::Sequence *B, const ScoringModel *scoreM)
Detailed Description
Definition at line 27 of file MetaCircularAlignment.h.
Constructor & Destructor Documentation
Circal::MetaCircularAlignment::MetaCircularAlignment (const bpp::Alphabet * alpha)
Definition at line 28 of file MetaCircularAlignment.cpp.
Circal::MetaCircularAlignment::~MetaCircularAlignment () [virtual]
Definition at line 34 of file MetaCircularAlignment.cpp.
Member Function Documentation
Alignment * Circal::MetaCircularAlignment::GotohAlignment (const bpp::Sequence * A, const bpp::Sequence * B, const ScoringModel * scoreM) [virtual]
Reimplemented from Circal::CircularAlignment.
Definition at line 38 of file MetaCircularAlignment.cpp.
References Circal::Alignment::BacktrackingGotoh(), Circal::Alignment::ForwardRecursionGotoh(), Circal::MatrixHelper::InitScoreMatrixWith(), and Circal::Alignment::matrix.
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/MetaCircularAlignment.h
Uni/workspace/CircalPP/src/MetaCircularAlignment.cpp