CircalPP: Circal::PseudoRotatedSequence Class Reference
Circal::PseudoRotatedSequence Class Reference
#include <PseudoRotatedSequence.h>
Public Member Functions
PseudoRotatedSequence (const SequenceProxy a)
virtual ~PseudoRotatedSequence ()
virtual unsigned int size () const
Get the number of elements in the list.
virtual int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as an int.
virtual std::string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as a character.
Provide direct access to the list content.
Warning
These operators allow you to modifiy the list content. No alphabet checking is performed for your modifications, so use with care, or consider using the setContent() method.
virtual const int & operator[] (unsigned int i) const
Operator [] overloaded for quick access to a character in list.
virtual int & operator[] (unsigned int i)
Operator [] overloaded for quick access to a character in list.
Public Member Functions inherited from Circal::RotatedSequence
RotatedSequence (const SequenceProxy a, const uint &i)
virtual ~RotatedSequence ()
std::string toString () const
Convert the list as a string.
Public Member Functions inherited from Circal::SequenceProxy
SequenceProxy (const std::string &name, const std::vector< int > &sequence, const bpp::Alphabet *alpha) throw (bpp::BadIntException)
SequenceProxy (const bpp::Sequence &sequence)
SequenceProxy (const std::string &name, const std::string &sequence, const bpp::Alphabet *alpha)
virtual ~SequenceProxy ()
void shuffle ()
void deleteElement (unsigned int pos) throw (bpp::IndexOutOfBoundsException)
void deleteElements (unsigned int pos, unsigned int len) throw (bpp::IndexOutOfBoundsException)
const bpp::Alphabet * getAlphabet () const
void setContent (const std::vector< int > &list) throw (bpp::BadIntException)
const std::vector< int > & getContent () const
void setElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void setElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
void addElement (const std::string &c) throw (bpp::BadCharException)
void addElement (unsigned int pos, const std::string &c) throw (bpp::BadCharException, bpp::IndexOutOfBoundsException)
void addElement (int v) throw (bpp::BadIntException)
void addElement (unsigned int pos, int v) throw (bpp::BadIntException, bpp::IndexOutOfBoundsException)
unsigned int size () const
std::string toString () const
std::string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
const int & operator[] (unsigned int i) const
int & operator[] (unsigned int i)
int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Detailed Description
Definition at line 28 of file PseudoRotatedSequence.h.
Constructor & Destructor Documentation
Circal::PseudoRotatedSequence::PseudoRotatedSequence (const SequenceProxy a)
Definition at line 25 of file PseudoRotatedSequence.cpp.
Circal::PseudoRotatedSequence::~PseudoRotatedSequence () virtual
Definition at line 30 of file PseudoRotatedSequence.cpp.
Member Function Documentation
std::string Circal::PseudoRotatedSequence::getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) virtual
Get the element at position 'pos' as a character.
Parameters
pos The position of the character to retrieve.
Reimplemented from Circal::RotatedSequence.
Definition at line 48 of file PseudoRotatedSequence.cpp.
Referenced by Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), and Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin().
int Circal::PseudoRotatedSequence::getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) virtual
Get the element at position 'pos' as an int.
Parameters
pos The position of the character to retrieve.
Reimplemented from Circal::RotatedSequence.
Definition at line 38 of file PseudoRotatedSequence.cpp.
Referenced by Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), and Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin().
const int & Circal::PseudoRotatedSequence::operator[] (unsigned int i) const virtual
Operator [] overloaded for quick access to a character in list.
Parameters
i The position to retrieve.
Returns
The integer value of character at position i.
Definition at line 56 of file PseudoRotatedSequence.cpp.
int & Circal::PseudoRotatedSequence::operator[] (unsigned int i) virtual
Operator [] overloaded for quick access to a character in list.
Parameters
i The position to retrieve.
Returns
The integer value of character at position i.
Definition at line 61 of file PseudoRotatedSequence.cpp.
unsigned int Circal::PseudoRotatedSequence::size () const virtual
Get the number of elements in the list.
Returns
The number of sites in the list.
Definition at line 33 of file PseudoRotatedSequence.cpp.
Referenced by Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::MatrixHelper::InitScoreMatrix3DWith(), and Circal::Output::TCoffeeLibHeader().
The documentation for this class was generated from the following files:
github/CircalPP/include/PseudoRotatedSequence.h
github/CircalPP/src/PseudoRotatedSequence.cpp