CircalPP: Circal::VertebrateMitochondrialGenomeAlphabet Class Reference
Circal::VertebrateMitochondrialGenomeAlphabet
Circal::VertebrateMitochondrialGenomeAlphabet Class Reference
#include <VertebrateMitochondrialGenomeAlphabet.h>
Public Member Functions
VertebrateMitochondrialGenomeAlphabet ()
VertebrateMitochondrialGenomeAlphabet (const ScoringModel *scm)
virtual ~VertebrateMitochondrialGenomeAlphabet ()
unsigned int getSize () const
unsigned int getNumberOfTypes () const
int getUnknownCharacterCode () const
std::string getAlphabetType () const
bool isUnresolved (int state) const
bool isUnresolved (const string &state) const
void convertModeltoAlphabet (const ScoringModel *scm)
Detailed Description
Definition at line 30 of file VertebrateMitochondrialGenomeAlphabet.h.
Constructor & Destructor Documentation
Circal::VertebrateMitochondrialGenomeAlphabet::VertebrateMitochondrialGenomeAlphabet ()
Definition at line 26 of file VertebrateMitochondrialGenomeAlphabet.cpp.
Circal::VertebrateMitochondrialGenomeAlphabet::VertebrateMitochondrialGenomeAlphabet (const ScoringModel * scm) [explicit]
Definition at line 30 of file VertebrateMitochondrialGenomeAlphabet.cpp.
References convertModeltoAlphabet().
Circal::VertebrateMitochondrialGenomeAlphabet::~VertebrateMitochondrialGenomeAlphabet () [virtual]
Definition at line 36 of file VertebrateMitochondrialGenomeAlphabet.cpp.
Member Function Documentation
unsigned int Circal::VertebrateMitochondrialGenomeAlphabet::getSize () const
Definition at line 39 of file VertebrateMitochondrialGenomeAlphabet.cpp.
unsigned int Circal::VertebrateMitochondrialGenomeAlphabet::getNumberOfTypes () const
Definition at line 44 of file VertebrateMitochondrialGenomeAlphabet.cpp.
Referenced by isUnresolved().
int Circal::VertebrateMitochondrialGenomeAlphabet::getUnknownCharacterCode () const
Definition at line 49 of file VertebrateMitochondrialGenomeAlphabet.cpp.
string Circal::VertebrateMitochondrialGenomeAlphabet::getAlphabetType () const
Definition at line 54 of file VertebrateMitochondrialGenomeAlphabet.cpp.
bool Circal::VertebrateMitochondrialGenomeAlphabet::isUnresolved (int state) const
Definition at line 59 of file VertebrateMitochondrialGenomeAlphabet.cpp.
References getNumberOfTypes().
Referenced by isUnresolved().
bool Circal::VertebrateMitochondrialGenomeAlphabet::isUnresolved (const string & state) const
Definition at line 64 of file VertebrateMitochondrialGenomeAlphabet.cpp.
References isUnresolved().
void Circal::VertebrateMitochondrialGenomeAlphabet::convertModeltoAlphabet (const ScoringModel * scm)
Definition at line 70 of file VertebrateMitochondrialGenomeAlphabet.cpp.
References Circal::ScoringModel::constitEnd(), Circal::ScoringModel::constitStart(), and Circal::ScoringModel::GetModelSize().
Referenced by VertebrateMitochondrialGenomeAlphabet().
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/VertebrateMitochondrialGenomeAlphabet.h
Uni/workspace/CircalPP/src/VertebrateMitochondrialGenomeAlphabet.cpp