CircalPP: Circal::MultipleAlignmentFactory Class Reference
Circal::MultipleAlignmentFactory Class Reference
#include <MultipleAlignmentFactory.h>
Public Member Functions
MultipleAlignmentFactory ()
virtual ~MultipleAlignmentFactory ()
Alignment GotohalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, int &delta, bool verbose)
Alignment NMWalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, int &delta, bool verbose)
Public Member Functions inherited from Circal::AlignmentFactory
AlignmentFactory ()
virtual ~AlignmentFactory ()
virtual Alignment NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
Additional Inherited Members
Protected Member Functions inherited from Circal::AlignmentFactory
virtual void ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D)
virtual Alignment BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual void ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q)
virtual Alignment BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual Alignment BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, uint &i, uint &j)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
Protected Attributes inherited from Circal::AlignmentFactory
MatrixHelper matrix
Output prettyPrint
Detailed Description
Definition at line 29 of file MultipleAlignmentFactory.h.
Constructor & Destructor Documentation
Circal::MultipleAlignmentFactory::MultipleAlignmentFactory () explicit
Definition at line 26 of file MultipleAlignmentFactory.cpp.
Circal::MultipleAlignmentFactory::~MultipleAlignmentFactory () virtual
Definition at line 30 of file MultipleAlignmentFactory.cpp.
Member Function Documentation
Alignment Circal::MultipleAlignmentFactory::GotohalignMultiple (const bpp::VectorSequenceContainer * input, ScoringModel * scoreM, int & delta, bool verbose)
Definition at line 34 of file MultipleAlignmentFactory.cpp.
References Circal::Alignment::addSequence(), Circal::Alignment::getSequence(), and Circal::AlignmentFactory::GotohAlignment().
Referenced by doAllignment().
Alignment Circal::MultipleAlignmentFactory::NMWalignMultiple (const bpp::VectorSequenceContainer * input, ScoringModel * scoreM, int & delta, bool verbose)
Definition at line 63 of file MultipleAlignmentFactory.cpp.
References Circal::Alignment::addSequence(), Circal::Alignment::getSequence(), and Circal::AlignmentFactory::NeedlemanWunschAlignment().
The documentation for this class was generated from the following files:
github/CircalPP/include/MultipleAlignmentFactory.h
github/CircalPP/src/MultipleAlignmentFactory.cpp