CircalPP: Circal::MultipleAlignment Class Reference
Circal::MultipleAlignment
Circal::MultipleAlignment Class Reference
#include <MultipleAlignment.h>
Public Member Functions
MultipleAlignment (const bpp::Alphabet *alpha)
MultipleAlignment (const VectorSequenceContainer *input, const ScoringModel *scoreM)
virtual ~MultipleAlignment ()
void GotohalignMultiple (const VectorSequenceContainer *input, const ScoringModel *scoreM)
void NMWalignMultiple (const VectorSequenceContainer *input, const ScoringModel *scoreM)
MultipleAlignment * TopologicSortedAlignment (BoolMatrix G, const Alignment *pairWiseAlignments)
Detailed Description
Definition at line 30 of file MultipleAlignment.h.
Constructor & Destructor Documentation
Circal::MultipleAlignment::MultipleAlignment (const bpp::Alphabet * alpha) [explicit]
Definition at line 26 of file MultipleAlignment.cpp.
Referenced by TopologicSortedAlignment().
Circal::MultipleAlignment::MultipleAlignment (const VectorSequenceContainer * input, const ScoringModel * scoreM)
Definition at line 35 of file MultipleAlignment.cpp.
Circal::MultipleAlignment::~MultipleAlignment () [virtual]
Definition at line 31 of file MultipleAlignment.cpp.
Member Function Documentation
void Circal::MultipleAlignment::GotohalignMultiple (const VectorSequenceContainer * input, const ScoringModel * scoreM)
Definition at line 42 of file MultipleAlignment.cpp.
References Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::GotohAlignment(), Circal::Alignment::prettyPrint, and Circal::Alignment::set_origSize().
Referenced by Circal::MultipleCircularAlignment::MultipleCircularAlignment(), and Circal::MultipleMetaCircularAlignment::MultipleMetaCircularAlignment().
void Circal::MultipleAlignment::NMWalignMultiple (const VectorSequenceContainer * input, const ScoringModel * scoreM)
Definition at line 63 of file MultipleAlignment.cpp.
References Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::NeedlemanWunschAlignment(), and Circal::Alignment::prettyPrint.
MultipleAlignment * Circal::MultipleAlignment::TopologicSortedAlignment (BoolMatrix G, const Alignment * pairWiseAlignments)
Definition at line 92 of file MultipleAlignment.cpp.
References MultipleAlignment().
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/MultipleAlignment.h
Uni/workspace/CircalPP/src/MultipleAlignment.cpp