CircalPP: Circal::Output Class Reference
Circal::Output Class Reference
#include <Output.h>
Public Member Functions
Output ()
virtual ~Output ()
std::string SequencePrettyPrint (SequenceProxy A)
std::string AlignmentPrettyPrint (Alignment *aln)
std::string ScoreMatrixPrettyPrint (const SequenceProxy A, const SequenceProxy B, const ScoreMatrix &D)
std::string AdjacenceMatrixPrettyPrint (const BoolMatrix &G)
std::string TCoffeeLibHeader (const bpp::VectorSequenceContainer *input)
std::string TCoffeeAlignFormat (Alignment *aln, const bpp::VectorSequenceContainer *input)
std::string TCoffeeLibFooter (void)
std::string TCoffeeLibFormat (Alignment *aln, const bpp::VectorSequenceContainer *input)
Detailed Description
Definition at line 40 of file Output.h.
Constructor & Destructor Documentation
Circal::Output::Output ()
Definition at line 31 of file Output.cpp.
Circal::Output::~Output () virtual
Definition at line 35 of file Output.cpp.
Member Function Documentation
std::string Circal::Output::AdjacenceMatrixPrettyPrint (const BoolMatrix & G)
Definition at line 77 of file Output.cpp.
std::string Circal::Output::AlignmentPrettyPrint (Alignment * aln)
Definition at line 63 of file Output.cpp.
References Circal::Alignment::get_Score(), Circal::Alignment::getNumberOfSequences(), Circal::Alignment::getSequence(), and SequencePrettyPrint().
Referenced by Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), and Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple().
std::string Circal::Output::ScoreMatrixPrettyPrint (const SequenceProxy A, const SequenceProxy B, const ScoreMatrix & D)
Definition at line 40 of file Output.cpp.
References Circal::SequenceProxy::getChar(), and Circal::SequenceProxy::size().
std::string Circal::Output::SequencePrettyPrint (SequenceProxy A)
Definition at line 90 of file Output.cpp.
References Circal::SequenceProxy::getChar(), and Circal::SequenceProxy::size().
Referenced by AlignmentPrettyPrint().
std::string Circal::Output::TCoffeeAlignFormat (Alignment * aln, const bpp::VectorSequenceContainer * input)
Definition at line 102 of file Output.cpp.
References Circal::Alignment::get_offsetA(), Circal::Alignment::get_offsetB(), and Circal::Alignment::getSequence().
Referenced by doAllignment(), and TCoffeeLibFormat().
std::string Circal::Output::TCoffeeLibFooter (void)
Definition at line 175 of file Output.cpp.
Referenced by doAllignment(), and TCoffeeLibHeader().
std::string Circal::Output::TCoffeeLibFormat (Alignment * aln, const bpp::VectorSequenceContainer * input)
Definition at line 133 of file Output.cpp.
References Circal::Alignment::addSequence(), Circal::Alignment::getAlphabet(), Circal::Alignment::getNumberOfSequences(), Circal::Alignment::getSequence(), TCoffeeAlignFormat(), and TCoffeeLibHeader().
Referenced by doAllignment().
std::string Circal::Output::TCoffeeLibHeader (const bpp::VectorSequenceContainer * input)
Definition at line 152 of file Output.cpp.
References Circal::PseudoRotatedSequence::size(), and TCoffeeLibFooter().
Referenced by doAllignment(), and TCoffeeLibFormat().
The documentation for this class was generated from the following files:
github/CircalPP/include/Output.h
github/CircalPP/src/Output.cpp