CircalPP: Circal::MetaRotatedSequence Class Reference
Circal::MetaRotatedSequence
Circal::MetaRotatedSequence Class Reference
#include <MetaRotatedSequence.h>
Public Member Functions
MetaRotatedSequence (const bpp::Sequence *a)
virtual ~MetaRotatedSequence ()
virtual unsigned int size () const
Get the number of elements in the list.
virtual int getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as an int.
virtual string getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException)
Get the element at position 'pos' as a character.
Provide direct access to the list content.
Warning:
These operators allow you to modifiy the list content. No alphabet checking is performed for your modifications, so use with care, or consider using the setContent() method.
virtual const int & operator[] (unsigned int i) const
Operator [] overloaded for quick access to a character in list.
virtual int & operator[] (unsigned int i)
Operator [] overloaded for quick access to a character in list.
Detailed Description
Definition at line 28 of file MetaRotatedSequence.h.
Constructor & Destructor Documentation
Circal::MetaRotatedSequence::MetaRotatedSequence (const bpp::Sequence * a)
Definition at line 25 of file MetaRotatedSequence.cpp.
Circal::MetaRotatedSequence::~MetaRotatedSequence () [virtual]
Definition at line 30 of file MetaRotatedSequence.cpp.
Member Function Documentation
unsigned int Circal::MetaRotatedSequence::size () const [virtual]
Get the number of elements in the list.
Returns:
The number of sites in the list.
Definition at line 33 of file MetaRotatedSequence.cpp.
Referenced by getChar(), and getValue().
int Circal::MetaRotatedSequence::getValue (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) [virtual]
Get the element at position 'pos' as an int.
Parameters:
pos The position of the character to retrieve.
Reimplemented from Circal::RotatedSequence.
Definition at line 38 of file MetaRotatedSequence.cpp.
References size().
string Circal::MetaRotatedSequence::getChar (unsigned int pos) const throw (bpp::IndexOutOfBoundsException) [virtual]
Get the element at position 'pos' as a character.
Parameters:
pos The position of the character to retrieve.
Reimplemented from Circal::RotatedSequence.
Definition at line 47 of file MetaRotatedSequence.cpp.
References size().
const int & Circal::MetaRotatedSequence::operator[] (unsigned int i) const [virtual]
Operator [] overloaded for quick access to a character in list.
Parameters:
i The position to retrieve.
Returns:
The integer value of character at position i.
Reimplemented from Circal::RotatedSequence.
Definition at line 66 of file MetaRotatedSequence.cpp.
int & Circal::MetaRotatedSequence::operator[] (unsigned int i) [virtual]
Operator [] overloaded for quick access to a character in list.
Parameters:
i The position to retrieve.
Returns:
The integer value of character at position i.
Reimplemented from Circal::RotatedSequence.
Definition at line 71 of file MetaRotatedSequence.cpp.
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/MetaRotatedSequence.h
Uni/workspace/CircalPP/src/MetaRotatedSequence.cpp