CircalPP: Circal::ScoringModel Class Reference
Circal::ScoringModel
Circal::ScoringModel Class Reference
#include <ScoringModel.h>
Public Member Functions
ScoringModel ()
ScoringModel (const std::string &path)
ScoringModel (std::istream &input)
virtual ~ScoringModel ()
void read (const std::string &path)
void read (std::istream &input)
double ScoreOf (const std::string &A, const std::string &B) const
double ScoreOfGapOpen (const std::string A) const
double ScoreOfGapExtend (const std::string A) const
int GetModelSize (void) const
double BestOfTwo (const double A, const double B) const
double BestOfThree (const double A, const double B, const double C) const
void NormalizeScores (const double &maxValue)
ModelValues::const_iterator constitStart (void) const
ModelValues::const_iterator constitEnd (void) const
ModelValues::iterator itStart (void)
ModelValues::iterator itEnd (void)
Private Attributes
ModelValues model
Detailed Description
Definition at line 31 of file ScoringModel.h.
Constructor & Destructor Documentation
Circal::ScoringModel::ScoringModel ()
Definition at line 27 of file ScoringModel.cpp.
Circal::ScoringModel::ScoringModel (const std::string & path) [explicit]
Definition at line 30 of file ScoringModel.cpp.
References read().
Circal::ScoringModel::ScoringModel (std::istream & input) [explicit]
Definition at line 35 of file ScoringModel.cpp.
References read().
Circal::ScoringModel::~ScoringModel () [virtual]
Definition at line 40 of file ScoringModel.cpp.
Member Function Documentation
void Circal::ScoringModel::read (const std::string & path)
Definition at line 118 of file ScoringModel.cpp.
Referenced by ScoringModel().
void Circal::ScoringModel::read (std::istream & input)
Definition at line 43 of file ScoringModel.cpp.
References Circal::AlignmentSymbol::gapExtend, Circal::AlignmentSymbol::gapOpen, Circal::AlignmentSymbol::match, Circal::AlignmentSymbol::missmatch, model, Circal::AlignmentSymbol::negativeMatch, NormalizeScores(), Circal::AlignmentSymbol::symbol, and Circal::AlignmentSymbol::type.
double Circal::ScoringModel::ScoreOf (const std::string & A, const std::string & B) const
Definition at line 125 of file ScoringModel.cpp.
References BestOfTwo(), and model.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), and Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin().
double Circal::ScoringModel::ScoreOfGapOpen (const std::string A) const
Definition at line 158 of file ScoringModel.cpp.
References model.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), and Circal::MatrixHelper::InitializeScoreMatrixDistances().
double Circal::ScoringModel::ScoreOfGapExtend (const std::string A) const
Definition at line 163 of file ScoringModel.cpp.
References model.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::AlignmentFactory::BacktrackingNMW(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), and Circal::MatrixHelper::InitializeScoreMatrixDistances().
int Circal::ScoringModel::GetModelSize (void) const
Definition at line 168 of file ScoringModel.cpp.
References model.
Referenced by Circal::VertebrateMitochondrialGenomeAlphabet::convertModeltoAlphabet().
double Circal::ScoringModel::BestOfTwo (const double A, const double B) const
Definition at line 173 of file ScoringModel.cpp.
Referenced by Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::AlignmentFactory::BacktrackingGotohGlocal(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman(), Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), BestOfThree(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::CircularAlignmentFactory::GotohAlignment(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), ScoreOf(), Circal::MatrixHelper::SearchBestInColumn(), Circal::MatrixHelper::SearchBestInColumn3D(), Circal::MatrixHelper::SearchBestInRow(), Circal::MatrixHelper::SearchBestInRow3D(), and Circal::MatrixHelper::SearchBestPositionFrom().
double Circal::ScoringModel::BestOfThree (const double A, const double B, const double C) const
Definition at line 179 of file ScoringModel.cpp.
References BestOfTwo().
Referenced by Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin(), and Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin().
void Circal::ScoringModel::NormalizeScores (const double & maxValue)
Definition at line 206 of file ScoringModel.cpp.
References itEnd(), and itStart().
Referenced by read().
ModelValues::const_iterator Circal::ScoringModel::constitStart (void) const
Definition at line 187 of file ScoringModel.cpp.
References model.
Referenced by Circal::VertebrateMitochondrialGenomeAlphabet::convertModeltoAlphabet().
ModelValues::const_iterator Circal::ScoringModel::constitEnd (void) const
Definition at line 192 of file ScoringModel.cpp.
References model.
Referenced by Circal::VertebrateMitochondrialGenomeAlphabet::convertModeltoAlphabet().
ModelValues::iterator Circal::ScoringModel::itStart (void)
Definition at line 197 of file ScoringModel.cpp.
References model.
Referenced by NormalizeScores().
ModelValues::iterator Circal::ScoringModel::itEnd (void)
Definition at line 201 of file ScoringModel.cpp.
References model.
Referenced by NormalizeScores().
Member Data Documentation
ModelValues Circal::ScoringModel::model [private]
Definition at line 34 of file ScoringModel.h.
Referenced by constitEnd(), constitStart(), GetModelSize(), itEnd(), itStart(), read(), ScoreOf(), ScoreOfGapExtend(), and ScoreOfGapOpen().
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/ScoringModel.h
Uni/workspace/CircalPP/src/ScoringModel.cpp