CircalPP: Circal::MultiplePseudoCircularAlignmentFactory Class Reference
Circal::MultiplePseudoCircularAlignmentFactory Class Reference
#include <MultiplePseudoCircularAlignmentFactory.h>
Public Member Functions
MultiplePseudoCircularAlignmentFactory ()
virtual ~MultiplePseudoCircularAlignmentFactory ()
Alignment NMWalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, const int &delta, bool verbose)
Alignment GotohalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, const int &delta, bool verbose)
Public Member Functions inherited from Circal::MultipleAlignmentFactory
MultipleAlignmentFactory ()
virtual ~MultipleAlignmentFactory ()
Alignment GotohalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, int &delta, bool verbose)
Alignment NMWalignMultiple (const bpp::VectorSequenceContainer *input, ScoringModel *scoreM, int &delta, bool verbose)
Public Member Functions inherited from Circal::AlignmentFactory
AlignmentFactory ()
virtual ~AlignmentFactory ()
virtual Alignment NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
Public Member Functions inherited from Circal::PseudoCircularAlignmentFactory
PseudoCircularAlignmentFactory ()
virtual ~PseudoCircularAlignmentFactory ()
Alignment NeedlemanWunschAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const int &delta, bool verbose=false)
Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, const int &delta, bool verbose)
Additional Inherited Members
Protected Member Functions inherited from Circal::AlignmentFactory
virtual void ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D)
virtual Alignment BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual void ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q)
virtual Alignment BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual Alignment BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, uint &i, uint &j)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
Protected Attributes inherited from Circal::AlignmentFactory
MatrixHelper matrix
Output prettyPrint
Detailed Description
Definition at line 28 of file MultiplePseudoCircularAlignmentFactory.h.
Constructor & Destructor Documentation
Circal::MultiplePseudoCircularAlignmentFactory::MultiplePseudoCircularAlignmentFactory () explicit
Definition at line 25 of file MultiplePseudoCircularAlignmentFactory.cpp.
Circal::MultiplePseudoCircularAlignmentFactory::~MultiplePseudoCircularAlignmentFactory () virtual
Definition at line 29 of file MultiplePseudoCircularAlignmentFactory.cpp.
Member Function Documentation
Alignment Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple (const bpp::VectorSequenceContainer * input, ScoringModel * scoreM, const int & delta, bool verbose)
Definition at line 33 of file MultiplePseudoCircularAlignmentFactory.cpp.
References Circal::Alignment::addSequence(), Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::getSequence(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::AlignmentFactory::prettyPrint.
Referenced by doAllignment().
Alignment Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple (const bpp::VectorSequenceContainer * input, ScoringModel * scoreM, const int & delta, bool verbose)
Definition at line 62 of file MultiplePseudoCircularAlignmentFactory.cpp.
References Circal::Alignment::addSequence(), Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::getSequence(), Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::prettyPrint.
The documentation for this class was generated from the following files:
github/CircalPP/include/MultiplePseudoCircularAlignmentFactory.h
github/CircalPP/src/MultiplePseudoCircularAlignmentFactory.cpp