CircalPP: Circal::PseudoCircularAlignmentFactory Class Reference
Circal::PseudoCircularAlignmentFactory Class Reference
#include <PseudoCircularAlignmentFactory.h>
Public Member Functions
PseudoCircularAlignmentFactory ()
virtual ~PseudoCircularAlignmentFactory ()
Alignment NeedlemanWunschAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const int &delta, bool verbose=false)
Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, const int &delta, bool verbose)
Public Member Functions inherited from Circal::AlignmentFactory
AlignmentFactory ()
virtual ~AlignmentFactory ()
virtual Alignment NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
Private Member Functions
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel *scoreM, const int &delta, ScoreMatrix3D *D, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel *scoreM, const int &delta, const ScoreMatrix3D *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel *scoreM, const int &delta, ScoreMatrix3D *D, ScoreMatrix3D *P, ScoreMatrix3D *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel *scoreM, const int &delta, const ScoreMatrix3D *D, const ScoreMatrix3D *P, const ScoreMatrix3D *Q, uint &i, uint &j, bool verbose=false)
Additional Inherited Members
Protected Member Functions inherited from Circal::AlignmentFactory
virtual void ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D)
virtual Alignment BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual void ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q)
virtual Alignment BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual Alignment BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, uint &i, uint &j)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
Protected Attributes inherited from Circal::AlignmentFactory
MatrixHelper matrix
Output prettyPrint
Detailed Description
Definition at line 29 of file PseudoCircularAlignmentFactory.h.
Constructor & Destructor Documentation
Circal::PseudoCircularAlignmentFactory::PseudoCircularAlignmentFactory ()
Definition at line 29 of file PseudoCircularAlignmentFactory.cpp.
Circal::PseudoCircularAlignmentFactory::~PseudoCircularAlignmentFactory () virtual
Definition at line 33 of file PseudoCircularAlignmentFactory.cpp.
Member Function Documentation
Alignment Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWaterman (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel * scoreM, const int & delta, const ScoreMatrix3D * D, uint & i, uint & j) private virtual
Definition at line 504 of file PseudoCircularAlignmentFactory.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getAlphabet(), Circal::PseudoRotatedSequence::getChar(), Circal::SequenceProxy::getChar(), Circal::PseudoRotatedSequence::getValue(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::PseudoRotatedSequence::size().
Referenced by NeedlemanWunschAlignment().
Alignment Circal::PseudoCircularAlignmentFactory::BacktrackingSmithWatermanAffin (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel * scoreM, const int & delta, const ScoreMatrix3D * D, const ScoreMatrix3D * P, const ScoreMatrix3D * Q, uint & i, uint & j, bool verbose = false) private virtual
Definition at line 212 of file PseudoCircularAlignmentFactory.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getAlphabet(), Circal::PseudoRotatedSequence::getChar(), Circal::SequenceProxy::getChar(), Circal::PseudoRotatedSequence::getValue(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::PseudoRotatedSequence::size().
Referenced by GotohAlignment().
double Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWaterman (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel * scoreM, const int & delta, ScoreMatrix3D * D, uint & bi, uint & bj) private virtual
! Changed from Original
! Changed from Original
Definition at line 379 of file PseudoCircularAlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::PseudoRotatedSequence::getChar(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), Circal::PseudoRotatedSequence::size(), and Circal::SequenceProxy::size().
Referenced by NeedlemanWunschAlignment().
double Circal::PseudoCircularAlignmentFactory::ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const PseudoRotatedSequence B, ScoringModel * scoreM, const int & delta, ScoreMatrix3D * D, ScoreMatrix3D * P, ScoreMatrix3D * Q, uint & bi, uint & bj) private virtual
Definition at line 37 of file PseudoCircularAlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::PseudoRotatedSequence::getChar(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), Circal::PseudoRotatedSequence::size(), and Circal::SequenceProxy::size().
Referenced by GotohAlignment().
Alignment Circal::PseudoCircularAlignmentFactory::GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel * scoreM, const int & delta, bool verbose)
Definition at line 668 of file PseudoCircularAlignmentFactory.cpp.
References BacktrackingSmithWatermanAffin(), Circal::AlignmentFactory::BacktrackingSmithWatermanAffin(), ForwardRecursionSmithWatermanAffin(), Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin(), Circal::MatrixHelper::InitScoreMatrix3DWith(), Circal::MatrixHelper::InitScoreMatrixWith(), Circal::AlignmentFactory::matrix, and Circal::SequenceProxy::size().
Referenced by doAllignment(), and Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple().
Alignment Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, const int & delta, bool verbose = false)
Definition at line 627 of file PseudoCircularAlignmentFactory.cpp.
References BacktrackingSmithWaterman(), Circal::AlignmentFactory::BacktrackingSmithWaterman(), ForwardRecursionSmithWaterman(), Circal::AlignmentFactory::ForwardRecursionSmithWaterman(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), Circal::MatrixHelper::InitScoreMatrix3DWith(), Circal::AlignmentFactory::matrix, and Circal::SequenceProxy::size().
Referenced by Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple().
The documentation for this class was generated from the following files:
github/CircalPP/include/PseudoCircularAlignmentFactory.h
github/CircalPP/src/PseudoCircularAlignmentFactory.cpp