CircalPP: Circal::CircularAlignment Class Reference
Circal::CircularAlignment
Circal::CircularAlignment Class Reference
#include <CircularAlignment.h>
Public Member Functions
CircularAlignment (const bpp::Alphabet *alpha)
virtual ~CircularAlignment ()
virtual Alignment * NeedlemanWunschAlignment (const bpp::Sequence *A, const bpp::Sequence *B, const ScoringModel *scoreM)
virtual Alignment * GotohAlignment (const bpp::Sequence *A, const bpp::Sequence *B, const ScoringModel *scoreM)
Detailed Description
Definition at line 28 of file CircularAlignment.h.
Constructor & Destructor Documentation
Circal::CircularAlignment::CircularAlignment (const bpp::Alphabet * alpha) [explicit]
Definition at line 28 of file CircularAlignment.cpp.
Circal::CircularAlignment::~CircularAlignment () [virtual]
Definition at line 33 of file CircularAlignment.cpp.
Member Function Documentation
Alignment * Circal::CircularAlignment::NeedlemanWunschAlignment (const bpp::Sequence * A, const bpp::Sequence * B, const ScoringModel * scoreM) [virtual]
Reimplemented from Circal::Alignment.
Definition at line 56 of file CircularAlignment.cpp.
References Circal::Alignment::get_Score(), and Circal::Alignment::NeedlemanWunschAlignment().
Alignment * Circal::CircularAlignment::GotohAlignment (const bpp::Sequence * A, const bpp::Sequence * B, const ScoringModel * scoreM) [virtual]
Reimplemented from Circal::Alignment.
Reimplemented in Circal::MetaCircularAlignment.
Definition at line 37 of file CircularAlignment.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::Alignment::get_Score(), and Circal::Alignment::GotohAlignment().
The documentation for this class was generated from the following files:
Uni/workspace/CircalPP/src/CircularAlignment.h
Uni/workspace/CircalPP/src/CircularAlignment.cpp