CircalPP: Circal::CircularAlignmentFactory Class Reference
Circal::CircularAlignmentFactory Class Reference
#include <CircularAlignmentFactory.h>
Public Member Functions
CircularAlignmentFactory ()
virtual ~CircularAlignmentFactory ()
Alignment NeedlemanWunschAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, int &delta, bool verbose=false)
Alignment GotohAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, int &delta, bool verbose=false)
Public Member Functions inherited from Circal::AlignmentFactory
AlignmentFactory ()
virtual ~AlignmentFactory ()
virtual Alignment NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
Additional Inherited Members
Protected Member Functions inherited from Circal::AlignmentFactory
virtual void ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D)
virtual Alignment BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual void ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q)
virtual Alignment BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual Alignment BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, uint &i, uint &j)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
Protected Attributes inherited from Circal::AlignmentFactory
MatrixHelper matrix
Output prettyPrint
Detailed Description
Definition at line 27 of file CircularAlignmentFactory.h.
Constructor & Destructor Documentation
Circal::CircularAlignmentFactory::CircularAlignmentFactory ()
Definition at line 27 of file CircularAlignmentFactory.cpp.
Circal::CircularAlignmentFactory::~CircularAlignmentFactory () virtual
Definition at line 31 of file CircularAlignmentFactory.cpp.
Member Function Documentation
Alignment Circal::CircularAlignmentFactory::GotohAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, int & delta, bool verbose = false)
Definition at line 35 of file CircularAlignmentFactory.cpp.
References Circal::AlignmentFactory::BacktrackingGotohGlobal(), Circal::ScoringModel::BestOfTwo(), Circal::AlignmentFactory::ForwardRecursionGotoh(), Circal::MatrixHelper::InitScoreMatrixWith(), Circal::AlignmentFactory::matrix, and Circal::SequenceProxy::size().
Referenced by doAllignment().
Alignment Circal::CircularAlignmentFactory::NeedlemanWunschAlignment (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, int & delta, bool verbose = false)
Definition at line 84 of file CircularAlignmentFactory.cpp.
References Circal::AlignmentFactory::BacktrackingNMW(), Circal::ScoringModel::BestOfTwo(), Circal::AlignmentFactory::ForwardRecursionNMW(), Circal::MatrixHelper::InitScoreMatrixWith(), Circal::AlignmentFactory::matrix, and Circal::SequenceProxy::size().
The documentation for this class was generated from the following files:
github/CircalPP/include/CircularAlignmentFactory.h
github/CircalPP/src/CircularAlignmentFactory.cpp