CircalPP: Circal::MatrixHelper Class Reference
Circal::MatrixHelper Class Reference
#include <MatrixHelper.h>
Public Member Functions
MatrixHelper ()
virtual ~MatrixHelper ()
ScoreMatrix InitializeScoreMatrixDistances (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM)
ScoreMatrix InitScoreMatrixWith (const SequenceProxy A, const SequenceProxy B, const double &init)
ScoreMatrix3D InitScoreMatrix3DWith (const SequenceProxy A, const PseudoRotatedSequence B, const int &delta, const double &init)
BoolMatrix CreateAdjacenceGraph (Alignment *pairWiseAlignments, int biggestSequenceSize)
void CutRowFromTo (ScoreMatrix *D, const uint &start, const uint &end)
void CutColumnFromTo (ScoreMatrix *D, const uint &start, const uint &end)
double SearchBestPositionFrom (const ScoreMatrix *M, uint &i, uint &j, const ScoringModel *scoreM)
int SearchBestInRow (const ScoreMatrix *M, const ScoringModel *scoreM, const uint &start, const uint &row)
int SearchBestInRow3D (const ScoreMatrix3D *M, const ScoringModel *scoreM, const uint &start, const uint &row, uint &k)
int SearchBestInColumn (const ScoreMatrix *M, const ScoringModel *scoreM, const uint &start, const uint &column)
int SearchBestInColumn3D (const ScoreMatrix3D *M, const ScoringModel *scoreM, const uint &start, const uint &column, uint &k)
Detailed Description
Definition at line 41 of file MatrixHelper.h.
Constructor & Destructor Documentation
Circal::MatrixHelper::MatrixHelper ()
Definition at line 29 of file MatrixHelper.cpp.
Circal::MatrixHelper::~MatrixHelper () virtual
Definition at line 33 of file MatrixHelper.cpp.
Member Function Documentation
BoolMatrix Circal::MatrixHelper::CreateAdjacenceGraph (Alignment * pairWiseAlignments, int biggestSequenceSize)
Definition at line 123 of file MatrixHelper.cpp.
References Circal::Alignment::getNumberOfSequences(), and Circal::Alignment::getSequence().
void Circal::MatrixHelper::CutColumnFromTo (ScoreMatrix * D, const uint & start, const uint & end)
Definition at line 51 of file MatrixHelper.cpp.
void Circal::MatrixHelper::CutRowFromTo (ScoreMatrix * D, const uint & start, const uint & end)
Definition at line 36 of file MatrixHelper.cpp.
ScoreMatrix Circal::MatrixHelper::InitializeScoreMatrixDistances (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM)
Definition at line 70 of file MatrixHelper.cpp.
References Circal::SequenceProxy::getChar(), InitScoreMatrixWith(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::AlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::SmithWaterman().
ScoreMatrix3D Circal::MatrixHelper::InitScoreMatrix3DWith (const SequenceProxy A, const PseudoRotatedSequence B, const int & delta, const double & init)
Definition at line 108 of file MatrixHelper.cpp.
References Circal::PseudoRotatedSequence::size(), and Circal::SequenceProxy::size().
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment().
ScoreMatrix Circal::MatrixHelper::InitScoreMatrixWith (const SequenceProxy A, const SequenceProxy B, const double & init)
Definition at line 100 of file MatrixHelper.cpp.
References Circal::SequenceProxy::size().
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), Circal::AlignmentFactory::GotohAlignment(), InitializeScoreMatrixDistances(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and Circal::AlignmentFactory::SmithWatermanAffin().
int Circal::MatrixHelper::SearchBestInColumn (const ScoreMatrix * M, const ScoringModel * scoreM, const uint & start, const uint & column)
Definition at line 190 of file MatrixHelper.cpp.
References Circal::ScoringModel::BestOfTwo().
Referenced by SearchBestPositionFrom().
int Circal::MatrixHelper::SearchBestInColumn3D (const ScoreMatrix3D * M, const ScoringModel * scoreM, const uint & start, const uint & column, uint & k)
Definition at line 208 of file MatrixHelper.cpp.
References Circal::ScoringModel::BestOfTwo().
int Circal::MatrixHelper::SearchBestInRow (const ScoreMatrix * M, const ScoringModel * scoreM, const uint & start, const uint & row)
Definition at line 149 of file MatrixHelper.cpp.
References Circal::ScoringModel::BestOfTwo().
Referenced by SearchBestPositionFrom().
int Circal::MatrixHelper::SearchBestInRow3D (const ScoreMatrix3D * M, const ScoringModel * scoreM, const uint & start, const uint & row, uint & k)
Definition at line 168 of file MatrixHelper.cpp.
References Circal::ScoringModel::BestOfTwo().
double Circal::MatrixHelper::SearchBestPositionFrom (const ScoreMatrix * M, uint & i, uint & j, const ScoringModel * scoreM)
Definition at line 230 of file MatrixHelper.cpp.
References Circal::ScoringModel::BestOfTwo(), SearchBestInColumn(), and SearchBestInRow().
The documentation for this class was generated from the following files:
github/CircalPP/include/MatrixHelper.h
github/CircalPP/src/MatrixHelper.cpp