CircalPP: Circal::AlignmentFactory Class Reference
Circal::AlignmentFactory Class Reference
#include <AlignmentFactory.h>
Public Member Functions
AlignmentFactory ()
virtual ~AlignmentFactory ()
virtual Alignment NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
virtual Alignment SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel *scoreM, bool verbose=false)
Protected Member Functions
virtual void ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D)
virtual Alignment BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual void ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q)
virtual Alignment BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual Alignment BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
virtual double ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, uint &i, uint &j)
virtual Alignment BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, uint &i, uint &j)
virtual double ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, ScoreMatrix *D, ScoreMatrix *P, ScoreMatrix *Q, uint &bi, uint &bj)
virtual Alignment BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel *scoreM, const ScoreMatrix *D, const ScoreMatrix *P, const ScoreMatrix *Q, uint &i, uint &j)
Protected Attributes
MatrixHelper matrix
Output prettyPrint
Detailed Description
Definition at line 33 of file AlignmentFactory.h.
Constructor & Destructor Documentation
Circal::AlignmentFactory::AlignmentFactory ()
Definition at line 29 of file AlignmentFactory.cpp.
Circal::AlignmentFactory::~AlignmentFactory () virtual
Definition at line 34 of file AlignmentFactory.cpp.
Member Function Documentation
Alignment Circal::AlignmentFactory::BacktrackingGotohGlobal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel * scoreM, const ScoreMatrix * D, const ScoreMatrix * P, const ScoreMatrix * Q, uint & i, uint & j) protected virtual
Definition at line 224 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getAlphabet(), Circal::SequenceProxy::getChar(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), and GotohAlignment().
Alignment Circal::AlignmentFactory::BacktrackingGotohGlocal (const SequenceProxy outA, const SequenceProxy outB, ScoringModel * scoreM, const ScoreMatrix * D, const ScoreMatrix * P, const ScoreMatrix * Q, uint & i, uint & j) protected virtual
Definition at line 85 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getAlphabet(), Circal::SequenceProxy::getChar(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Alignment Circal::AlignmentFactory::BacktrackingNMW (const SequenceProxy outA, const SequenceProxy outB, ScoringModel * scoreM, const ScoreMatrix * D, uint & i, uint & j) protected virtual
Definition at line 407 of file AlignmentFactory.cpp.
References Circal::SequenceProxy::getAlphabet(), Circal::SequenceProxy::getChar(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Referenced by Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and NeedlemanWunschAlignment().
Alignment Circal::AlignmentFactory::BacktrackingSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, const ScoreMatrix * D, uint & i, uint & j) protected virtual
Definition at line 556 of file AlignmentFactory.cpp.
References Circal::SequenceProxy::getAlphabet(), Circal::SequenceProxy::getChar(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and SmithWaterman().
Alignment Circal::AlignmentFactory::BacktrackingSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, const ScoreMatrix * D, const ScoreMatrix * P, const ScoreMatrix * Q, uint & i, uint & j) protected virtual
Definition at line 712 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getAlphabet(), Circal::SequenceProxy::getChar(), Circal::SequenceProxy::getValue(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), and Circal::ScoringModel::ScoreOfGapOpen().
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and SmithWatermanAffin().
void Circal::AlignmentFactory::ForwardRecursionGotoh (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, ScoreMatrix * D, ScoreMatrix * P, ScoreMatrix * Q) protected virtual
Definition at line 37 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::SequenceProxy::size().
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), and GotohAlignment().
void Circal::AlignmentFactory::ForwardRecursionNMW (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, ScoreMatrix * D) protected virtual
Definition at line 376 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::SequenceProxy::size().
Referenced by Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), and NeedlemanWunschAlignment().
double Circal::AlignmentFactory::ForwardRecursionSmithWaterman (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, ScoreMatrix * D, uint & i, uint & j) protected virtual
Definition at line 509 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::SequenceProxy::size().
Referenced by Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), and SmithWaterman().
double Circal::AlignmentFactory::ForwardRecursionSmithWatermanAffin (const SequenceProxy A, const SequenceProxy B, ScoringModel * scoreM, ScoreMatrix * D, ScoreMatrix * P, ScoreMatrix * Q, uint & bi, uint & bj) protected virtual
Definition at line 643 of file AlignmentFactory.cpp.
References Circal::ScoringModel::BestOfThree(), Circal::ScoringModel::BestOfTwo(), Circal::SequenceProxy::getChar(), Circal::ScoringModel::ScoreOf(), Circal::ScoringModel::ScoreOfGapExtend(), Circal::ScoringModel::ScoreOfGapOpen(), and Circal::SequenceProxy::size().
Referenced by Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and SmithWatermanAffin().
Alignment Circal::AlignmentFactory::GotohAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel * scoreM, bool verbose = false) virtual
Definition at line 863 of file AlignmentFactory.cpp.
References BacktrackingGotohGlobal(), ForwardRecursionGotoh(), Circal::MatrixHelper::InitScoreMatrixWith(), and matrix.
Referenced by Circal::MultipleAlignmentFactory::GotohalignMultiple().
Alignment Circal::AlignmentFactory::NeedlemanWunschAlignment (const SequenceProxy inA, const SequenceProxy inB, ScoringModel * scoreM, bool verbose = false) virtual
Definition at line 846 of file AlignmentFactory.cpp.
References BacktrackingNMW(), ForwardRecursionNMW(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), and matrix.
Referenced by Circal::MultipleAlignmentFactory::NMWalignMultiple().
Alignment Circal::AlignmentFactory::SmithWaterman (const SequenceProxy inA, const SequenceProxy inB, ScoringModel * scoreM, bool verbose = false) virtual
Definition at line 880 of file AlignmentFactory.cpp.
References BacktrackingSmithWaterman(), ForwardRecursionSmithWaterman(), Circal::MatrixHelper::InitializeScoreMatrixDistances(), and matrix.
Alignment Circal::AlignmentFactory::SmithWatermanAffin (const SequenceProxy inA, const SequenceProxy inB, ScoringModel * scoreM, bool verbose = false) virtual
Definition at line 894 of file AlignmentFactory.cpp.
References BacktrackingSmithWatermanAffin(), ForwardRecursionSmithWatermanAffin(), Circal::MatrixHelper::InitScoreMatrixWith(), and matrix.
Member Data Documentation
MatrixHelper Circal::AlignmentFactory::matrix protected
Definition at line 37 of file AlignmentFactory.h.
Referenced by Circal::CircularAlignmentFactory::GotohAlignment(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), GotohAlignment(), Circal::CircularAlignmentFactory::NeedlemanWunschAlignment(), Circal::PseudoCircularAlignmentFactory::NeedlemanWunschAlignment(), NeedlemanWunschAlignment(), SmithWaterman(), and SmithWatermanAffin().
Output Circal::AlignmentFactory::prettyPrint protected
Definition at line 38 of file AlignmentFactory.h.
Referenced by Circal::MultiplePseudoCircularAlignmentFactory::GotohalignMultiple(), and Circal::MultiplePseudoCircularAlignmentFactory::NMWalignMultiple().
The documentation for this class was generated from the following files:
github/CircalPP/include/AlignmentFactory.h
github/CircalPP/src/AlignmentFactory.cpp