CircalPP: Uni/workspace/CircalPP/src/main.cpp File Reference
Uni » workspace » CircalPP » src
main.cpp File Reference
#include "MultipleCircularAlignmentFactory.h"
#include "MultiplePseudoCircularAlignmentFactory.h"
#include "ScoringModel.h"
#include "ExtendedFasta.h"
#include "Output.h"
#include "RandomSequence.h"
#include "VertebrateMitochondrialGenomeAlphabet.h"
#include <Seq/alphabets>
#include <NumCalc/RandomTools.h>
#include <iostream>
#include <fstream>
#include <sstream>
Functions
int main (int args, char *argv[])
Function Documentation
int main (int args, char * argv[])
Definition at line 37 of file main.cpp.
References Circal::Output::AlignmentPrettyPrint(), Circal::Alignment::get_Score(), Circal::PseudoCircularAlignmentFactory::GotohAlignment(), and Circal::CircularAlignmentFactory::GotohAlignment().